return {
	marks = {
		{ lat = "33.000", long = "70.065", mark = "Location dot green.svg", marksize = "6", label = "[[Miramshah]]", link = "Miramshah", label_size = "70", position = "top"},
        { lat = "33.716667", long = "73.066667", mark = "Location dot green.svg", marksize = "30", label = "[[Islamabad]]", link = "Islamabad", label_size = "180", position = "top" },
		{ lat = "33.6", long = "73.033333", mark = "Location dot green.svg", marksize = "36", label = "[[Rawalpindi]]", link = "Rawalpindi", label_size = "200", position = "bottom" },
		{ lat = "32.15", long = "74.183333", mark = "Location dot green.svg", marksize = "32", label = "[[Gujranwala]]", link = "Gujranwala", label_size = "180", position = "top" },
		{ lat = "31.429167", long = "73.078889", mark = "Location dot green.svg", marksize = "40", label = "[[Faisalabad]]", link = "Faisalabad", label_size = "220", position = "bottom" },
		{ lat = "31.549722", long = "74.343611", mark = "Location dot green.svg", marksize = "48", label = "[[Lahore]]", link = "Lahore", label_size = "250", position = "top" },
		{ lat = "34.016667", long = "71.583333", mark = "Location dot green.svg", marksize = "35", label = "[[Peshawar]]", link = "Peshawar", label_size = "200", position = "bottom" },
		{ lat = "30.197778", long = "71.469722", mark = "Location dot green.svg", marksize = "33", label = "[[Multan]]", link = "Multan", label_size = "200", position = "left" },
		{ lat = "29.395556", long = "71.683611", mark = "Location dot green.svg", marksize = "30", label = "[[Bahawalpur]]", link = "Bahawalpur", label_size = "180", position = "bottom" },
		{ lat = "30.223333", long = "67.577222", mark = "Location dot green.svg", marksize = "6", label = "[[Khost, Pakistan|Khost]]", link = "Khost, Pakistan", label_size = "70", position = "top" },
		{ lat = "29.55", long = "67.883333", mark = "Location dot green.svg", marksize = "10", label = "[[Sibi]]", link = "Sibi", label_size = "70", position = "bottom" },
		{ lat = "31.35", long = "69.45", mark = "Location dot green.svg", marksize = "9", label = "[[Zhob]]", link = "Zhob", label_size = "70", position = "top" },
		{ lat = "35.921944", long = "74.289167", mark = "Location dot green.svg", marksize = "22", label = "[[Gilgit]]", link = "Gilgit", label_size = "125", position = "top" },
		{ lat = "34.35", long = "73.466667", mark = "Location dot green.svg", marksize = "12", label = "[[Muzaffarabad]]", link = "Muzaffarabad", label_size = "100", position = "top" },
		{ lat = "34.25", long = "72.25", mark = "Location dot green.svg", marksize = "27", label = "[[Mardan]]", link = "Mardan", label_size = "150", position = "top" },
		{ lat = "34.155833", long = "73.219444", mark = "Location dot green.svg", marksize = "25", label = "[[Abbottabad]]", link = "Abbottabad", label_size = "150", position = "top" },
		{ lat = "35.846111", long = "71.785833", mark = "Location dot green.svg", marksize = "12", label = "[[Chitral]]", link = "Chitral", label_size = "100", position = "bottom" },
		{ lat = "36.283333", long = "72.516667", mark = "Location dot green.svg", marksize = "19", label = "[[Mastuj]]", link = "Mastuj", label_size = "125", position = "bottom" },
		{ lat = "34.783333", long = "72.366667", mark = "Location dot green.svg", marksize = "18", label = "[[Mingora]]", link = "Mingora", label_size = "125", position = "top" },
		{ lat = "33.988", long = "72.955", mark = "Location dot green.svg", marksize = "10", label = "[[Haripur]]", link = "Haripur", label_size = "70", position = "top" },
		{ lat = "32.605278", long = "70.914444", mark = "Location dot green.svg", marksize = "18", label = "[[Lakki Marwat]]", link = "Lakki Marwat", label_size = "125", position = "bottom" },
		{ lat = "31.928611", long = "70.459167", mark = "Location dot green.svg", marksize = "7", label = "[[Kulachi]]", link = "Kulachi", label_size = "70", position = "bottom" },
		{ lat = "34.74", long = "71.53", mark = "Location dot green.svg", marksize = "12", label = "[[Khaar]]", link = "Khaar", label_size = "100", position = "bottom" },
		{ lat = "34.101111", long = "71.145556", mark = "Location dot green.svg", marksize = "8", label = "[[Landi Kotal]]", link = "Landi Kotal", label_size = "70", position = "bottom" },
		{ lat = "33.899167", long = "70.100833", mark = "Location dot green.svg", marksize = "16", label = "[[Parachinar]]", link = "Parachinar", label_size = "100", position = "right" },
		{ lat = "32.6886", long = "69.8356", mark = "Location dot green.svg", marksize = "7", label = "[[Razmak]]", link = "Razmak", label_size = "70", position = "top" },
		{ lat = "32.9", long = "69.7356", mark = "Location dot green.svg", marksize = "7", label = "[[Datta Khel]]", link = "Datta Khel", label_size = "70", position = "right" },
		{ lat = "32.9", long = "69.6356", mark = "Location dot green.svg", marksize = "7", label = "[[Shawal Valley]]", link = "Shawal Valley", label_size = "0" },
		{ lat = "32.304722", long = "69.570278", mark = "Location dot green.svg", marksize = "13", label = "[[Wana, Pakistan|Wana]]", link = "Wana, Pakistan", label_size = "100", position = "top" },
		{ lat = "32.333056", long = "70.114444", mark = "Location dot green.svg", marksize = "6", label = "[[Jandola]]", link = "Jandola", label_size = "70", position = "top" },
		{ lat = "33.683543", long = "71.519687", mark = "Location dot green.svg", marksize = "8", label = "[[Darra Adam Khel]]", link = "Darra Adam Khel", label_size = "70", position = "bottom" },
		{ lat = "32.13", long = "70.23", mark = "Location dot green.svg", marksize = "10", label = "[[Tank, Pakistan|Tank]]", link = "Tank, Pakistan", label_size = "70", position = "top" },
		{ lat = "25.379", long = "68.368", mark = "Location dot green.svg", marksize = "28", label = "[[Hyderabad]]", link = "Hyderabad, Sindh", label_size = "200", position = "top" },
		{ lat = "28.61", long = "77.23", mark = "Dot yellow ff4.svg", marksize = "57", label = "[[Dehli]]", link = "Dehli", label_size = "300", position = "top" },
		{ lat = "18.975", long = "72.826", mark = "Dot yellow ff4.svg", marksize = "52", label = "[[Mumbai]]", link = "Mumbai", label_size = "300", position = "top" },
		{ lat = "32.73", long = "74.87", mark = "Dot yellow ff4.svg", marksize = "18", label = "[[Jammu]]", link = "Jammu", label_size = "125", position = "right" },
		{ lat = "34.09", long = "74.79", mark = "Dot yellow ff4.svg", marksize = "28", label = "[[Srinagar]]", link = "Srinagar", label_size = "200", position = "right" },
		{ lat = "34.145", long = "77.567", mark = "Dot yellow ff4.svg", marksize = "11", label = "[[Leh]]", link = "Leh", label_size = "100", position = "top" },
		{ lat = "23.7", long = "90.367", mark = "Dot green 0d0.svg", marksize = "58", label = "[[Dhaka]]", link = "Dhaka", label_size = "300", position = "top" },
		{ lat = "6.934", long = "79.843", mark = "Location dot magenta.svg", marksize = "28", label = "[[Colombo]]", link = "Colombo", label_size = "200", position = "top" },
		{ lat = "27.7", long = "85.333", mark = "Location dot red.svg", marksize = "29", label = "[[Kathmandu]]", link = "Kathmandu", label_size = "200", position = "top" },
		{ lat = "29.65", long = "91.117", mark = "Location dot orange.svg", marksize = "22", label = "[[Lhasa]]", link = "Lhasa", label_size = "150", position = "top" },
		{ lat = "27.467", long = "89.642", mark = "Location dot magenta.svg", marksize = "15", label = "[[Thimphu]]", link = "Thimphu", label_size = "150", position = "top" },
		{ lat = "27.1", long = "93.62", mark = "Dot yellow ff4.svg", marksize = "8", label = "[[Itanagar]]", link = "Itanagar", label_size = "100", position = "top" },
		{ lat = "12.967", long = "77.567", mark = "Dot yellow ff4.svg", marksize = "48", label = "[[Bangalore]]", link = "Bangalore", label_size = "250", position = "top" },
		{ lat = "13.083", long = "80.267", mark = "Dot yellow ff4.svg", marksize = "46", label = "[[Chennai]]", link = "Chennai", label_size = "250", position = "top" },
		{ lat = "17.37", long = "78.48", mark = "Dot yellow ff4.svg", marksize = "45", label = "[[Hyderabad]]", link = "Hyderabad", label_size = "250", position = "top" },
		{ lat = "23.03", long = "72.58", mark = "Dot yellow ff4.svg", marksize = "43", label = "[[Ahmedabad]]", link = "Ahmedabad", label_size = "250", position = "top" },
		{ lat = "22.567", long = "88.367", mark = "Dot yellow ff4.svg", marksize = "40", label = "[[Kolkata]]", link = "Kolkata", label_size = "220", position = "top" },
		{ lat = "21.170", long = "72.831", mark = "Dot yellow ff4.svg", marksize = "40", label = "[[Surat]]", link = "Surat", label_size = "220", position = "top" },
		{ lat = "18.520", long = "73.857", mark = "Dot yellow ff4.svg", marksize = "36", label = "[[Pune]]", link = "Pune", label_size = "200", position = "top" },
		{ lat = "26.9", long = "75.8", mark = "Dot yellow ff4.svg", marksize = "34", label = "[[Jaipur]]", link = "Jaipur", label_size = "200", position = "top" },
		{ lat = "26.8", long = "80.9", mark = "Dot yellow ff4.svg", marksize = "33", label = "[[Lucknow]]", link = "Lucknow", label_size = "200", position = "top" },
		{ lat = "11.668", long = "92.738", mark = "Dot yellow ff4.svg", marksize = "12", label = "[[Port Blair]]", link = "Port Blair", label_size = "100", position = "top" },
		{ lat = "26.141", long = "91.791", mark = "Dot yellow ff4.svg", marksize = "6", label = "[[Dispur]]", link = "Dispur", label_size = "80", position = "top" },
		{ lat = "25.6", long = "85.1", mark = "Dot yellow ff4.svg", marksize = "28", label = "[[Patna]]", link = "Patna", label_size = "200", position = "top" },
		{ lat = "30.75", long = "76.78", mark = "Dot yellow ff4.svg", marksize = "27", label = "[[Chandigarh]]", link = "Chandigarh", label_size = "180", position = "top" },
		{ lat = "21.25", long = "81.63", mark = "Dot yellow ff4.svg", marksize = "28", label = "[[Raipur]]", link = "Raipur", label_size = "200", position = "top" },
		{ lat = "20.27", long = "73.02", mark = "Dot yellow ff4.svg", marksize = "11", label = "[[Silvassa]]", link = "Silvassa", label_size = "100", position = "top" },
		{ lat = "20.42", long = "72.85", mark = "Dot yellow ff4.svg", marksize = "15", label = "[[Daman, Daman and Diu|Daman]]", link = "Daman, Daman and Diu", label_size = "150", position = "top" },
		{ lat = "15.499", long = "73.828", mark = "Dot yellow ff4.svg", marksize = "8", label = "[[Panaji]]", link = "Panaji", label_size = "100", position = "top" },
		{ lat = "23.223", long = "72.65", mark = "Dot yellow ff4.svg", marksize = "22", label = "[[Gandhinagar]]", link = "Gandhinagar", label_size = "150", position = "top" },
		{ lat = "21.15", long = "79.09", mark = "Dot yellow ff4.svg", marksize = "31", label = "[[Nagpur]]", link = "Nagpur", label_size = "200", position = "top" },
		{ lat = "24.82", long = "93.95", mark = "Dot yellow ff4.svg", marksize = "24", label = "[[Imphal]]", link = "Imphal", label_size = "150", position = "top" },
		{ lat = "23.25", long = " 77.417", mark = "Dot yellow ff4.svg", marksize = "33", label = "[[Bhopal]]", link = "Bhopal", label_size = "200", position = "top" },
		{ lat = "11.931", long = "79.785", mark = "Dot yellow ff4.svg", marksize = "26", label = "[[Pondicherry]]", link = "Pondicherry", label_size = "180", position = "top" },
		{ lat = "30.91", long = "75.85", mark = "Dot yellow ff4.svg", marksize = "29", label = "[[Ludhiana]]", link = "Ludhiana", label_size = "200", position = "top" },
		{ lat = "23.36", long = "85.33", mark = "Dot yellow ff4.svg", marksize = "28", label = "[[Ranchi]]", link = "Ranchi", label_size = "200", position = "top" },
		{ lat = "18.619", long = "73.804", mark = "Dot yellow ff4.svg", marksize = "29", label = "[[Pimpri-Chinchwad]]", link = "Pimpri-Chinchwad", label_size = "200", position = "top" },
		{ lat = "26.45", long = "80.332", mark = "Dot yellow ff4.svg", marksize = "32", label = "[[Kanpur]]", link = "Kanpur", label_size = "200", position = "top" },
		{ lat = "17.688333", long = "83.219", mark = "Dot yellow ff4.svg", marksize = "30", label = "[[Visakhapatnam]]", link = "Visakhapatnam", label_size = "200", position = "top" },
		{ lat = "22.717", long = "75.847", mark = "Dot yellow ff4.svg", marksize = "31", label = "[[Indore]]", link = "Indore", label_size = "200", position = "top" },
		{ lat = "19.172", long = "72.957", mark = "Dot yellow ff4.svg", marksize = "29", label = "[[Thane]]", link = "Thane", label_size = "200", position = "top" },
		{ lat = "31.103", long = "77.172", mark = "Dot yellow ff4.svg", marksize = "16", label = "[[Shimla]]", link = "Shimla", label_size = "150", position = "top" },
		{ lat = "9.97", long = "76.28", mark = "Dot yellow ff4.svg", marksize = "26", label = "[[Kochi]]", link = "Kochi", label_size = "180", position = "top" },
		{ lat = "27.33", long = "88.62", mark = "Dot yellow ff4.svg", marksize = "11", label = "[[Gangtok]]", link = "Gangtok", label_size = "100", position = "top" },
		{ lat = "9.9", long = "78.1", mark = "Dot yellow ff4.svg", marksize = "28", label = "[[Madurai]]", link = "Madurai", label_size = "200", position = "top" },
		{ lat = "22.367", long = "91.8", mark = "Dot green 0d0.svg", marksize = "31", label = "[[Chittagong]]", link = "Chittagong", label_size = "200", position = "top" },
		{ lat = "23.833", long = "91.267", mark = "Dot yellow ff4.svg", marksize = "24", label = "[[Agartala]]", link = "Agartala", label_size = "150", position = "top" },
		{ lat = "23.727", long = "92.718", mark = "Dot yellow ff4.svg", marksize = "21", label = "[[Aizawl]]", link = "Aizawl", label_size = "150", position = "top" },
		{ lat = "35.4", long = "77.1", mark = "4x4dot-yellow.svg", marksize = "16", label = "[[Siachen Glacier]]", link = "Siachen Glacier", label_size = "100", position = "right" },
	},
	containerArgs = {
		'India',
		float = 'center',
		width = '3000',
		caption = [=['''Hold cursor over location to display name; click to go to location row in the "table of cities and towns" (if available).'''<br/>
*[[File:Dot yellow ff4.svg|11px]] Under control of the [[Politics of India|Indian Government]] and Allies (outside of this country)
*[[File:Location dot green.svg|11px]] Under control of the [[Politics of Pakistan|Pakistani Government]], and allied militias
*[[File:Location dot blue.svg|11px]] Under control of Northeastern separatists in India, [[Tamil Eelam]] or local forces (e.g. [[United Liberation Front of Asom]])
*[[File:Dot green 0d0.svg|11px]] Under control of [[Politics of Bangladesh|Bangladeshi Government]], [[Politics of Maldives|Maldivian Government]], [[Khalistan movement]], Kashmiri nationalist separatists and Baloch nationalist separatists (unrelated of Bangladeshi government, e.g. [[Jammu Kashmir Liberation Front]])
*[[File:Location dot red.svg|11px]] Under control of [[Politics of Nepal|Nepali Government]], [[Naxalite]]-[[Maoist|Maoists]] (in India), [[Communist|Communists]] (in Bangladesh), [[Shia|Shi'ite]] militias (in Pakistan)
*[[File:Location dot orange.svg|11px]] Under control of [[Politics of China|Chinese Government]]
*[[File:Location dot magenta.svg|11px]] Under control of [[Politics of Sri Lanka|Sri Lankan Government]] and [[Politics of Bhutan|Bhutanese Government]]
*[[File:Map-dot-grey-68a.svg|11px]] Under control of the Non-ISIL [[Islamism|Islamist]] militias and Islamistic separatists (e.g. [[Tehrik-e-Taliban Pakistan|TTIP]] and [[Lashkar-e-Taiba]])
*[[File:Location dot black.svg|11px]] Under control of [[Islamic State of Iraq and the Levant]]
[[File:80x80-yellow-green-anim.gif|11px]] Contested; [[File:Abm-yellow-icon.png|15px]] Army base; [[File:Fighter-jet-yellow-icon.svg|13px]] Airport or air base (jet); [[File:Helicopter-yellow-icon.svg|13px]] Airport or air base (helicopter); [[File:Anchor_pictogram.svg|12px]] Major port, naval base, or oil terminal; [[File:Mountain pass 12x12 n.svg|20px]] Border post; [[File:Arch dam 12x12 w.svg|16px]] Dam; [[File:Icon NuclearPowerPlant-black.svg|12px]] Industrial complex; [[File:Gota02.svg|10px]] Oil fields; [[File:map-circle-blue.svg|11px]] besieged
<br>
Rural presence [[File:4x4dot-green.svg|11px]] [[File:4x4dot-green.svg|11px]]

<br>'''2 nested circles: Controlled by inner, but under siege by outer'''<br>'''Large circle with different icons inside: Situation in military/economic installations in and around city''']=]
	}
}