return {
	marks = {
		--Border crossings
		{ lat = "30.133", long = "9.400", mark = "Mountain pass 12x12 se.svg", marksize = "18", label = "[[Ghadames|Ghadames Border Crossing]]", link = "Ghadames", label_size = "0" },
		{ lat = "24.713", long = "10.206", mark = "Mountain pass 12x12 ne.svg", marksize = "18", label = "[[Tin El Koum|Aysayn border crossing]]", link = "Tin El Koum", label_size = "0" },
		{ lat = "31.578", long = "25.064", mark = "Mountain pass 12x12 se.svg", marksize = "18", label = "[[Musaid|Musaid Border Crossing]]", link = "Musaid", label_size = "0" },
		{ lat = "22.647", long = "14.200", mark = "Mountain pass 12x12 n.svg", marksize = "18", label = "[[Tumu|Tumu Border Crossing]]", link = "Tumu", label_size = "0" },
		{ lat = "33.148", long = "11.563", mark = "Mountain pass 12x12 e.svg", marksize = "18", label = "[[Ras Ajdir|Ras Ajdir border crossing]]", link = "Ras Ajdir", label_size = "0" },
		{ lat = "31.980", long = "10.684", mark = "Mountain pass 12x12 n.svg", marksize = "18", label = "[[Wazzin|Wazzin Border Crossing]]", link = "Wazzin", label_size = "0" },
		    -- dotsize vs population
			-- Capital 									Size: 35	-- label size: 140
			-- population > 1M	: 						size: 28  	-- label size: 130
			-- population < 1M & population > 500k	  	Size: 20  	-- label size: 120
			-- population < 500k & population > 100k	Size: 18 	-- label size: 100sa
			-- population < 100k & population > 25k     Size: 14    -- label size: 90
			-- population < 25k & population > 10k		Size: 12 	-- label size: 0 or 80
			-- population < 10k							Size: 8	    -- label size: 0 or 80
		{ lat = "32.080", long = "20.140", mark = "Location dot red.svg", marksize = "28", label = "[[Benghazi]]", link = "Benghazi", label_size = "130", position = "left" },
		{ lat = "31.449", long = "15.254", mark = "Dot green ff4.svg", marksize = "6", label = "[[Abu Qurayn]]", label_size = "80", link = "Abu Qurayn", position = "right" },
		{ lat = "33.0742", long = "11.7512", mark = "Dot green ff4.svg", marksize = "6", label = "[[Abu Kemash]]", label_size = "0", link = "Abu Kemash" },
		{ lat = "32.033", long = "12.866", mark = "Dot green ff4.svg", marksize = "6", label = "[[Al Asabi‘ah]]", label_size = "0", link = "Al Asabi‘ah" },
		{ lat = "31.643", long = "12.805", mark = "Dot green ff4.svg", marksize = "6", label = "[[Ash Shuqayqah]]", label_size = "0", link = "Ash Shuqayqah" },
		{ lat = "32.357", long = "13.09", mark = "Dot green ff4.svg", marksize = "6", label = "[[Arrigi'at]]", label_size = "0" },
		{ lat = "31.969", long = "12.75", mark = "Dot green ff4.svg", marksize = "6", label = "[[Algwalish]]", label_size = "0" },
		{ lat = "31.647", long = "15.272", mark = "Dot green ff4.svg", marksize = "6", label = "[[Al Hayshah]]", label_size = "0", link = "Al Hayshah" },
		{ lat = "31.522", long = "14.757", mark = "Dot green ff4.svg", marksize = "6", label = "[[Sadadah]]", label_size = "0", link = "Sadadah" },
		{ lat = "31.664", long = "14.723", mark = "Dot green ff4.svg", marksize = "4", label = "[[Bi’r al Mi‘zan]]", label_size = "0", link = "Bi’r al Mi‘zan" },
		{ lat = "32.002", long = "10.835", mark = "Dot green ff4.svg", marksize = "6", label = "[[Al Gahazaya]]", label_size = "0", link = "Al Gahazaya" },
		{ lat = "31.86", long = "11.159", mark = "Dot green ff4.svg", marksize = "6", label = "[[Al Majabirah]]", label_size = "0", link = "Al Majabirah" },
		{ lat = "30.585", long = "15.413", mark = "Dot green ff4.svg", marksize = "6", label = "[[Abu Najim]]", label_size = "0", link = "Abu Najim" },
		{ lat = "31.012", long = "15.318", mark = "Dot green ff4.svg", marksize = "5", label = "[[al Baghlah]]", label_size = "0", link = "al Baghlah" },
		{ lat = "27.813", long = "16.387", mark = "Location dot red.svg", marksize = "6", label = "[[Fuqaha, Libya|Fuqaha]]", label_size = "0", link = "Fuqaha, Libya" },
		{ lat = "31.851", long = "15.103", mark = "Abm-lime-icon.png", marksize = "6", label = "[[Abu Qurayn-Misrata Checkpoint]]", label_size = "0", },
		{ lat = "32.188", long = "20.596", mark = "Location dot red.svg", marksize = "8", label = "[[Abyar, Libya|Abyar]]", label_size = "90", link = "Abyar,_Libya", position = "right" },
		{ lat = "27.5", long = "13.266", mark = "Dot green ff4.svg", marksize = "8", label = "[[Adiri, Libya|Adiri]]", label_size = "80", link = "Adiri, Libya", position = "top" },
		{ lat = "32.684", long = "13.183", mark = "Dot green ff4.svg", marksize = "10", label = "[[Qasr bin Ghashir|Bin Ghashir]]", label_size = "70", link = "Qasr bin Ghashir", position = "right" },
		{ lat = "32.531", long = "13.021", mark = "Dot green ff4.svg", marksize = "8", label = "[[‘Aziziya]]", label_size = "80", link = "Al Aziziyah", position = "left" },
		{ lat = "32.633", long = "12.874", mark = "Dot green ff4.svg", marksize = "6", label = "[[An Nasiriyah]]", label_size = "0", link = "An Nasiriyah" },
		{ lat = "32.678", long = "12.873", mark = "Dot green ff4.svg", marksize = "6", label = "[[Az Zahra]]", label_size = "0", link = "Az Zahra" },
        { lat = "32.828", long = "11.635", mark = "Dot green ff4.svg", marksize = "7", label = "[[Al Assah]]", label_size = "0", link = "Al Assah" },
        { lat = "32.430", long = "12.920", mark = "Dot green ff4.svg", marksize = "5", label = "[[Al Kasarat]]", label_size = "0", link = "Al Assah" },
        { lat = "32.274", long = "13.029", mark = "Dot green ff4.svg", marksize = "5", label = "[[Bu Ghaylan]]", label_size = "0", link = "Al Assah" },
        { lat = "32.175", long = "12.857", mark = "Dot green ff4.svg", marksize = "6", label = "[[Arrabitah]]", label_size = "0", link = "Arrabitah" },
        { lat = "32.158", long = "12.841", mark = "Dot green ff4.svg", marksize = "6", label = "[[Al Manasir]]", label_size = "0", link = "Al Manasir" },
	    { lat = "31.331", long = "12.774", mark = "Dot green ff4.svg", marksize = "6", label = "[[Fessano]]", label_size = "0", link = "Fessano" },
		{ lat = "32.719", long = "12.857", mark = "Dot green ff4.svg", marksize = "6", label = "[[Al Ma`murah]]", label_size = "0", link = "Al Ma`muraha" },
		{ lat = "32.809", long = "13.273", mark = "Dot green ff4.svg", marksize = "8", label = "[[Ain Zara]]", label_size = "0", link = "Ain Zara" },
		{ lat = "32.713", long = "13.067", mark = "Dot green ff4.svg", marksize = "6", label = "[[Al Sawani]]", label_size = "0", link = "Al Sawani" },
		{ lat = "29.108", long = "21.287", mark = "Location dot red.svg", marksize = "8", label = "[[Awjila]]", label_size = "0", link = "Awjila" },
		{ lat = "32.787", long = "21.998", mark = "Location dot red.svg", marksize = "8", label = "[[Al Abraq]]", label_size = "0", link = "Al Abraq, Libya" },
		{ lat = "32.760", long = "21.751", mark = "Location dot red.svg", marksize = "18", label = "[[Bayda, Libya|Al Bayda]]", label_size = "100", link = "Bayda,_Libya", position = "left" },
		{ lat = "32.291", long = "20.257", mark = "Location dot red.svg", marksize = "8", label = "[[Al Kuwayfiyah]]", label_size = "0", link = "Al Kuwayfiyah" },
	    { lat = "32.351", long = "20.302", mark = "Location dot red.svg", marksize = "8", label = "[[Sidi Khalifah]]", label_size = "0", link = "Sidi Khalifah" },	
		{ lat = "32.802", long = "12.879", mark = "Dot green ff4.svg", marksize = "8", label = "[[Al Maya]]", label_size = "0", link = "Al Maya" },
		{ lat = "30.386", long = "13.583", mark = "Dot green ff4.svg", marksize = "7", label = "[[Al Qaryat]]", label_size = "0", },
		{ lat = "32.168", long = "13.389", mark = "Dot green ff4.svg", marksize = "8", label = "[[Al ‘Urban]]", label_size = "70", link = "Al ‘Urban", position = "right" },
		{ lat = "31.371", long = "15.569", mark = "Dot green ff4.svg", marksize = "7", label = "[[Al-Washakh]]", label_size = "0", link = "Al-Washakh" },
		{ lat = "32.757", long = "12.376", mark = "Dot green ff4.svg", marksize = "8", label = "[[Ajaylat]]", label_size = "0", link = "Ajaylat" },
        { lat = "30.759", long = "20.223", mark = "Location dot red.svg", marksize = "14", label = "[[Ajdabiya]]", label_size = "100", link = "Ajdabiya", position = "right" },
	    { lat = "32.767", long = "22.250", mark = "Location dot red.svg", marksize = "10", label = "[[Al Qubbah]]", label_size = "80", link = "Al Qubbah", position = "bottom" },
		{ lat = "32.332", long = "23.061", mark = "Location dot red.svg", marksize = "8", label = "[[At Tamimi]]", label_size = "0", link = "At Tamimi" },
		{ lat = "32.745", long = "12.724", mark = "Dot green ff4.svg", marksize = "18", label = "[[Zawiya, Libya|Zawiya]]", label_size = "80", link = "Zawiya, Libya", position = "top" },
		{ lat = "31.904", long = "10.811", mark = "Dot green ff4.svg", marksize = "6", label = "[[Ayn al Ghazaya]]", label_size = "0", link = "Ayn al Ghazaya" },
		{ lat = "32.760", long = "22.387", mark = "Location dot red.svg", marksize = "8", label = "[[Ayn Marrah]]", label_size = "0", link = "Ayn Marrah" },
		{ lat = "31.756", long = "14.02", mark = "Dot green ff4.svg", marksize = "14", label = "[[Bani Walid]]", label_size = "90", link = "Bani Walid", position = "top" },
		{ lat = "32.792", long = "12.832", mark = "Abm-lime-icon.png", marksize = "5", label = "[[Hawiat gate]]", label_size = "0"  },
		{ lat = "31.656", long = "13.994", mark = "Abm-lime-icon.png", marksize = "10", label = "[[May 28 Brigade HQ]]", label_size = "0"  },
		{ lat = "31.333", long = "13.052", mark = "Abm-lime-icon.png", marksize = "6", label = "[[al Batamah Checkpoint(Butma Gate)]]", label_size = "0", },
		{ lat = "31.406", long = "13.994", mark = "Abm-lime-icon.png", marksize = "8", label = "[[Alforta Castle]]", label_size = "0" },
		{ lat = "31.414", long = "13.950", mark = "Dot green ff4.svg", marksize = "6", label = "[[Shumaykh]]", label_size = "0" },
		{ lat = "31.391", long = "13.983", mark = "Dot green ff4.svg", marksize = "4", label = "[[Bi’r Shumaykh]]", label_size = "0" },
		{ lat = "31.456", long = "13.994", mark = "Dot green ff4.svg", marksize = "6", label = "[[Al Shamikh]]", label_size = "0", link = "Al Shamikh" },
		{ lat = "31.340", long = "13.634", mark = "Dot green ff4.svg", marksize = "6", label = "[[Ras At Tabi]]", label_size = "0", link = "Ras At Tabi" },
		{ lat = "31.56", long = "14.313", mark = "Dot green ff4.svg", marksize = "4", label = "[[Al Ghaweil]]", label_size = "0" },
		{ lat = "31.528", long = "14.451", mark = "Dot green ff4.svg", marksize = "4", label = "[[Wadi Souf Al Jein]]", label_size = "0" },
		{ lat = "31.669", long = "14.734", mark = "Dot green ff4.svg", marksize = "6", label = "[[Gararat Al Katif]]", label_size = "0" },
		{ lat = "31.756", long = "25.086", mark = "Location dot red.svg", marksize = "8", label = "[[Bardia]]", label_size = "80", link = "Bardia", position = "top" },
		{ lat = "31.968", long = "14.602", mark = "Abm-lime-icon.png", marksize = "6", label = "[[Bi’r Dufan]]", label_size = "0" },
		{ lat = "31.878", long = "10.978", mark = "Dot green ff4.svg", marksize = "11", label = "[[Nalut]]", label_size = "70", link = "Nalut", position = "top" },
		{ lat = "32.077", long = "20.357", mark = "Location dot red.svg", marksize = "10", label = "[[Benina]]", label_size = "0", link = "Benina" },
		{ lat = "32.070", long = "20.444", mark = "Location dot red.svg", marksize = "8", label = "[[Ar Rajmah]]", label_size = "0", link = "Ar Rajmah" },
		{ lat = "30.807", long = "18.069", mark = "Location dot red.svg", marksize = "8", label = "[[Bin Jawad]]", label_size = "90", link = "Bin Jawad", position = "top" },
		{ lat = "30.727", long = "18.089", mark = "BSicon STRrf red.svg", marksize = "10", label = "[[Bin Jawad Dam]]", label_size = "0", link = "Bin Jawad Dam" },
		{ lat = "32.306", long = "12.641", mark = "Dot green ff4.svg", marksize = "8", label = "[[Bir Ghanam]]", label_size = "0", link = "Bir Ghanam" },
 		{ lat = "27.552", long = "14.265", mark = "Location dot red.svg", marksize = "12", label = "[[Brak, Libya|Brak]]", label_size = "90", link = "Brak, Libya", position = "bottom" },
		{ lat = "30.410", long = "19.570", mark = "Location dot red.svg", marksize = "8", label = "[[Brega]]", label_size = "80", link = "Brega", position = "top" },
		{ lat = "31.396", long = "15.725", mark = "Dot green ff4.svg", marksize = "4", label = "[[Buerat]]", label_size = "0" },
		{ lat = "32.766", long = "22.636", mark = "Location dot red.svg", marksize = "16", label = "[[Derna, Libya|Derna]]", label_size = "100", link = "Derna, Libya", position = "right" },
		{ lat = "31.132", long = "16.270", mark = "Location dot red.svg", marksize = "6", label = "[[Wadi Jarif]]", label_size = "0" },
		{ lat = "31.085", long = "16.388", mark = "Abm-red-icon.png", marksize = "6", label = "[[Al-Gabaybah]]", label_size = "0" },
		{ lat = "30.955", long = "13.581", mark = "Dot green ff4.svg", marksize = "6", label = "[[Wadi Marsit]]", label_size = "0" },
		{ lat = "31.136", long = "15.850", mark = "Dot green ff4.svg", marksize = "6", label = "[[Wadi al Bayy]]", label_size = "0" },
		{ lat = "30.371", long = "15.578", mark = "Dot green ff4.svg", marksize = "6", label = "[[Wadi Alloud]]", label_size = "0" },
		{ lat = "32.543", long = "13.287", mark = "Dot green ff4.svg", marksize = "5", label = "[[Wadi Al Rabie]]", label_size = "0"},
		{ lat = "32.276", long = "12.86", mark = "Dot green ff4.svg", marksize = "5", label = "[[Wadi Abu Shaybah]]", label_size = "0" },
		{ lat = "32.521", long = "13.105", mark = "Dot green ff4.svg", marksize = "4", label = "[[Bi'r 'Allaq]]", label_size = "0" },
		{ lat = "32.598", long = "13.174", mark = "Dot green ff4.svg", marksize = "4", label = "[[Suq as Sabt]]", label_size = "0" },
		{ lat = "32.591", long = "13.141", mark = "Dot green ff4.svg", marksize = "4", label = "[[Bi’r Sidi Musa]]", label_size = "0" },
		{ lat = "32.572", long = "13.108", mark = "Dot green ff4.svg", marksize = "4", label = "[[Sidi Farhat]]", label_size = "0" },
		{ lat = "32.570", long = "13.062", mark = "Dot green ff4.svg", marksize = "4", label = "[[Awlad Tulays]]", label_size = "0" },
		{ lat = "32.537", long = "13.057", mark = "Dot green ff4.svg", marksize = "4", label = "[[Bi’r al Mudaybighah]]", label_size = "0" },
		{ lat = "32.499", long = "13.141", mark = "Dot green ff4.svg", marksize = "4", label = "[[Bi’r al Mahazim]]", label_size = "0" },
		{ lat = "32.413", long = "13.239", mark = "Dot green ff4.svg", marksize = "5", label = "[[al-Hayy as-Sina'i]]", label_size = "0" },
		{ lat = "32.527", long = "13.219", mark = "Dot green ff4.svg", marksize = "6", label = "[[Tripoli District, Libya|Suq al Khamis]]", label_size = "0", link = "Tripoli District, Libya" },
		{ lat = "26.579", long = "12.919", mark = "Icon NuclearPowerPlant-green.svg", marksize = "6", label = "[[Disi agricultural project]]", label_size = "0" },
		{ lat = "32.452", long = "13.036", mark = "Icon NuclearPowerPlant-green.svg", marksize = "6", label = "[[Electric Power station]]", label_size = "0" },
		{ lat = "32.388", long = "13.235", mark = "Icon NuclearPowerPlant-green.svg", marksize = "6", label = "[[Souq Al-Khamis Cement Factory]]", label_size = "0" },
		{ lat = "32.295", long = "13.247", mark = "BSicon STRrf green.svg", marksize = "11", label = "[[Wadi al-Majnin al-Jurnia Dam]]", label_size = "0" },
		{ lat = "32.244", long = "13.136", mark = "BSicon STRrf green.svg", marksize = "11", label = "[[Wadi Gan Dam]]", label_size = "0" },
		{ lat = "30.256", long = "19.197", mark = "Location dot red.svg", marksize = "8", label = "[[El Agheila]]", label_size = "90", link = "El Agheila", position = "top" },
		{ lat = "30.291", long = "19.435", mark = "Location dot red.svg", marksize = "8", label = "[[Bashir, Libya|Bashir]]", label_size = "0" },
		{ lat = "32.564", long = "21.254", mark = "Location dot red.svg", marksize = "8", label = "[[El Bayyada]]", label_size = "0", link = "El Bayyada" },
		{ lat = "31.013", long = "17.447", mark = "Location dot red.svg", marksize = "6", label = "[[El Tesseyn]]", label_size = "0", link = "El Tesseyn" },
		{ lat = "32.4998", long = "20.703", mark = "Location dot red.svg", marksize = "6", label = "[[Farzoughah]]", label_size = "0", link = "Farzoughah" },
		{ lat = "32.493", long = "20.830", mark = "Location dot red.svg", marksize = "14", label = "[[Al Marj]]", label_size = "80", link = "Al Marj", position = "bottom" },
		{ lat = "26.529", long = "13.072", mark = "Location dot red.svg", marksize = "8", label = "[[Germa]]", label_size = "70", link = "Germa", position = "bottom" },
		{ lat = "26.646", long = "13.652", mark = "Location dot red.svg", marksize = "8", label = "[[Bint Bayah]]", label_size = "0" },
		{ lat = "30.125", long = "9.492", mark = "Dot green ff4.svg", marksize = "10", label = "[[Ghadames]]", label_size = "80", link = "Ghadames", position = "bottom"},
		{ lat = "30.133", long = "9.400", mark = "Dot green ff4.svg", marksize = "8", label = "[[Ghadames|Ghadames Border Crossing]]", label_size = "70", link = "Ghadames", position = "top"},
		{ lat = "30.168", long = "10.461", mark = "Dot green ff4.svg", marksize = "10", label = "[[Dirj]]", label_size = "0", link = "Dirj" },
		{ lat = "32.165", long = "13.018", mark = "Dot green ff4.svg", marksize = "16", label = "[[Gharyan]]", label_size = "80", link = "Gharyan", position = "top" },
		{ lat = "24.966", long = "10.184", mark = "Dot_green_ff4.svg", marksize = "10", label = "[[Ghat, Libya|Ghat]]", label_size = "80", link = "Ghat,_Libya", position = "right" },
		{ lat = "25.783", long = "10.56", mark = "Dot_green_ff4.svg", marksize = "7", label = "[[Al Awaynat]]", label_size = "70", link = "Al Awaynat", position = "top" },
		{ lat = "24.894", long = "10.184", mark = "Dot_green_ff4.svg", marksize = "5", label = "[[Al Barakat]]", label_size = "0", link = "Al Barakat" },
		{ lat = "24.955", long = "10.083", mark = "Dot_green_ff4.svg", marksize = "4", label = "[[Al-Fewat]]", label_size = "0", link = "Al-Fewat" },
		{ lat = "26.425", long = "14.305", mark = "Location dot red.svg", marksize = "8", label = "[[Ghadduwah]]", label_size = "70", link = "Ghadduwah", position = "top" },
		{ lat = "31.114", long = "17.150", mark = "Location dot red.svg", marksize = "5", label = "[[Al Sultan]]", label_size = "0", link = "Sultan,_Libya"  },
		{ lat = "31.160", long = "16.947", mark = "Location dot red.svg", marksize = "6", label = "[[Haush al Urjiyah]]", label_size = "0", link = "Haush al Urjiyah"  },
		{ lat = "31.154", long = "17.034", mark = "Location dot red.svg", marksize = "5", label = "[[Wadi al-Hunaywah]]", label_size = "0", link = "Wadi al-Hunaywah"  },
		{ lat = "31.135", long = "17.060", mark = "Location dot red.svg", marksize = "6", label = "[[Ard al Madniyah]]", label_size = "0", link = "Ard al Madniyah"  },
		{ lat = "31.083", long = "17.204", mark = "Location dot red.svg", marksize = "4", label = "[[Wadi Al Amra]]", label_size = "0", link = "Wadi Al Amra"  },
		{ lat = "31.053", long = "17.285", mark = "Location dot red.svg", marksize = "7", label = "[[Harawa]]", label_size = "70", link = "Harawa", position = "right" },	
		{ lat = "29.121", long = "15.940", mark = "Location dot red.svg", marksize = "12", label = "[[Hun, Libya|Hun]]", label_size = "70", link = "Hun, Libya", position = "bottom" },
		{ lat = "32.821", long = "13.011", mark = "Dot green ff4.svg", marksize = "12", label = "[[Janzur]]", label_size = "70", link = "Janzur", position = "top" },
		{ lat = "27.050", long = "14.250", mark = "Location dot red.svg", marksize = "8", label = "[[Jadid, Libya|Jadid]]", label_size = "80", link = "Jadid,_Libya", position = "left" },
		{ lat = "32.016", long = "11.5", mark = "Dot_green_ff4.svg", marksize = "10", label = "[[Badr, Libya|Badr]]", label_size = "70", link = "Badr, Libya", position = "top" },
        { lat = "31.950", long = "12.017", mark = "Dot green ff4.svg", marksize = "8", label = "[[Jadu, Libya|Jadu]]", label_size = "0", link = "Jadu, Libya" },
        { lat = "32.015", long = "11.355", mark = "Dot_green_ff4.svg", marksize = "7", label = "[[Tiji, Libya|Tiji]]", label_size = "0", link = "Tiji, Libya" },
        { lat = "32.0", long = "11.667", mark = "Dot_green_ff4.svg", marksize = "5", label = "[[Al Jawsh]]", label_size = "0" },
		{ lat = "31.883", long = "11.792", mark = "Dot_green_ff4.svg", marksize = "5", label = "[[Al Shiyab]]", label_size = "0" },
		{ lat = "31.997", long = "12.330", mark = "Location dot red.svg", marksize = "6", label = "[[Al-Rayaniya]]", label_size = "0" },
		{ lat = "29.033", long = "21.55", mark = "Location dot red.svg", marksize = "10", label = "[[Jalu]]", label_size = "80", link = "Jalu", position = "right" },
		{ lat = "29.216", long = "21.556", mark = "Location dot red.svg", marksize = "7", label = "[[Jakharrah]]", label_size = "0", link = "Jakharrah"  },
		{ lat = "32.850", long = "12.061", mark = "Dot green ff4.svg", marksize = "14", label = "[[Jumayl]]", label_size = "80", link = "Jumayl, Libya", position = "bottom" },
		{ lat = "32.887", long = "11.987", mark = "Dot green ff4.svg", marksize = "10", label = "[[Regdalin]]", label_size = "0", link = "Regdalin"  },
		{ lat = "32.843", long = "22.425", mark = "Location dot red.svg", marksize = "7", label = "[[Karsah]]", label_size = "0"  },
		{ lat = "24.196", long = "23.277", mark = "Location dot red.svg", marksize = "14", label = "[[Kufra]]", label_size = "90", link = "Kufra", position = "top" },
		{ lat = "32.067", long = "12.691", mark = "Dot green ff4.svg", marksize = "10", label = "[[Kikla]]", label_size = "70", link = "Kikla", position = "top" },
		{ lat = "32.644", long = "14.270", mark = "Dot green ff4.svg", marksize = "18", label = "[[Al Khums]]", label_size = "80", link = "Al Khums", position = "top" },
	 	{ lat = "32.779", long = "22.142", mark = "Location dot red.svg", marksize = "7", label = "[[Lamluda]]", label_size = "0", link = "Lamluda" },	
		{ lat = "32.799", long = "13.000", mark = "Dot green ff4.svg", marksize = "6", label = "[[Mashashita]]", label_size = "0", link = "Mashashita" },
		{ lat = "32.816", long = "12.95", mark = "Dot green ff4.svg", marksize = "6", label = "[[Sayyad]]", label_size = "0" },
		{ lat = "32.752", long = "21.626", mark = "Location dot red.svg", marksize = "8", label = "[[Massah]]", label_size = "0", link = "Massah, Libya" },
		{ lat = "32.628", long = "21.471", mark = "Location dot red.svg", marksize = "7", label = "[[Zaiwa Al Arqoub]]", label_size = "0" },
		{ lat = "32.537", long = "21.574", mark = "Location dot red.svg", marksize = "7", label = "[[Qandula]]", label_size = "0", link = "Qandula" },
		{ lat = "32.591", long = "21.717", mark = "Location dot red.svg", marksize = "7", label = "[[Slonta]]", label_size = "0", link = "Slonta" },
		{ lat = "32.840", long = "21.521", mark = "Location dot red.svg", marksize = "7", label = "[[Al Haniyah]]", label_size = "0", link = "Haniyah, Libya" },
		{ lat = "32.915", long = "21.629", mark = "Location dot red.svg", marksize = "7", label = "[[Al Hamamah]]", label_size = "0", link = "Al Hamamah" },
		{ lat = "32.688", long = "21.906", mark = "Location dot red.svg", marksize = "7", label = "[[Ahqaf al Jabbarat]]", label_size = "0" },
		{ lat = "32.731", long = "21.902", mark = "Location dot red.svg", marksize = "7", label = "[[Qirnada]]", label_size = "0", link = "Qirnada" },
		{ lat = "31.905", long = "24.482", mark = "Location dot red.svg", marksize = "7", label = "[[Kambut]]", label_size = "0", link = "Kambut" },
		{ lat = "31.954", long = "24.200", mark = "Location dot red.svg", marksize = "7", label = "[[Al Qarah]]", label_size = "0" },
		{ lat = "32.139", long = "23.479", mark = "Location dot red.svg", marksize = "7", label = "[[Al Qardabah]]", label_size = "0" },
		{ lat = "29.1", long = "19.199", mark = "Location dot red.svg", marksize = "8", label = "[[Maradah]]", label_size = "80", link = "Maradah", position = "top"},
		{ lat = "32.595", long = "22.764", mark = "Location dot red.svg", marksize = "8", label = "[[Martuba]]", label_size = "0", link = "Martuba" },
		{ lat = "32.363", long = "15.110", mark = "Dot green ff4.svg", marksize = "22", label = "[[Misrata]]", label_size = "120", link = "Misrata", position = "top" },
		{ lat = "32.263", long = "15.210", mark = "Abm-lime-icon.png", marksize = "6", label = "[[Misrata-Tawergha Checkpoint]]", label_size = "0" },
		{ lat = "31.228", long = "16.198", mark = "Abm-lime-icon.png", marksize = "6", label = "[[Area 30 Checkpoint]]", label_size = "0" },
		{ lat = "31.186", long = "16.549", mark = "Abm-red-icon.png", marksize = "8", label = "[[Tagrift Military camp]]", label_size = "0" },
		{ lat = "31.005", long = "16.454", mark = "Abm-red-icon.png", marksize = "8", label = "[[Al-Saadi Brigade Weapons Storage]]", label_size = "0" },
		{ lat = "31.456", long = "12.977", mark = "Dot green ff4.svg", marksize = "10", label = "[[Mizda]]", label_size = "90", link = "Mizda", position = "top" },
        { lat = "32.582", long = "14.040", mark = "Dot green ff4.svg", marksize = "12", label = "[[Msallata]]", label_size = "80", link = "Msallata", position = "bottom" },
		{ lat = "25.9155", long = "13.921", mark = "Location dot red.svg", marksize = "10", label = "[[Murzuk]]", label_size = "70", link = "Murzuk", position = "top" },
		{ lat = "25.915", long = "13.904", mark = "Abm-red-icon.png", marksize = "6", label = "[[Old Murzuk Castle]]", label_size = "0" },
		{ lat = "31.690", long = "25.048", mark = "Location dot red.svg", marksize = "8", label = "[[Musaid]]", label_size = "80", link = "Musaid", position = "left" },
		{ lat = "31.578", long = "25.064", mark = "Location dot red.svg", marksize = "8", label = "[[Musaid|Musaid border crossing]]", label_size = "70", link = "Musaid", position = "bottom" },		
		{ lat = "31.931", long = "19.985", mark = "Location dot red.svg", marksize = "8", label = "[[M‘reisa]]", label_size = "0", link = "M‘reisa" },
		{ lat = "31.383", long = "13.283", mark = "Dot green ff4.svg", marksize = "7", label = "[[Nasmah]]", label_size = "70", link = "Nasmah", position = "top" },
		{ lat = "31.981", long = "19.999", mark = "Anchor pictogram red.svg", marksize = "10", label = "[[M‘reisa Port]]", label_size = "0", link = "M‘reisa Port" },
		{ lat = "30.899", long = "17.746", mark = "Location dot red.svg", marksize = "6", label = "[[Om El-Gendell]]", label_size = "0" },
		{ lat = "30.876", long = "17.792", mark = "Location dot red.svg", marksize = "6", label = "[[Al Masuda]]", label_size = "0" },
		{ lat = "30.909", long = "17.712", mark = "Location dot red.svg", marksize = "6", label = "[[Mersa al Uwayja]]", label_size = "0" },
		{ lat = "31.195", long = "16.689", mark = "Location dot red.svg", marksize = "7", label = "[[Al Suwawaah]]", label_size = "0" },
		{ lat = "32.739", long = "13.085", mark = "Dot green ff4.svg", marksize = "6", label = "[[Kharimiyah]]", label_size = "0" },
		{ lat = "30.777", long = "17.835", mark = "Location dot red.svg", marksize = "8", label = "[[Nofaliya]]", label_size = "70", link = "Nofaliya", position = "left" },
		{ lat = "30.819", long = "17.885", mark = "Location dot red.svg", marksize = "6", label = "[[Nofaliya Farms]]", label_size = "0" },
		{ lat = "31.659", long = "20.016", mark = "Location dot red.svg", marksize = "8", label = "[[Qaminis]]", label_size = "90", link = "Qaminis", position = "left" },
		{ lat = "31.064", long = "16.659", mark = "Location dot red.svg", marksize = "6", label = "[[Qasr Abu Hadi]]", label_size = "0", link = "Qasr Abu Hadi" },
		{ lat = "31.09", long = "16.529", mark = "Location dot red.svg", marksize = "4", label = "[[Jabbanat Sidi Bu Baqr]]", label_size = "0" },
		{ lat = "31.135", long = "16.54", mark = "Location dot red.svg", marksize = "5", label = "[[Gharbiyat]]", label_size = "0", link = "Gharbiyat" },
		{ lat = "24.929", long = "14.555", mark = "Location dot red.svg", marksize = "8", label = "[[Qatrun]]", label_size = "80", link = "Qatrun", position = "left" },
		{ lat = "32.726", long = "22.022", mark = "Location dot red.svg", marksize = "8", label = "[[Qayqab]]", label_size = "0", link = "Qayqab" },
		{ lat = "32.630", long = "21.675", mark = "Location dot red.svg", marksize = "8", label = "[[Qaryat ‘Umar al Mukhtar]]", label_size = "0", link = "Qaryat ‘Umar al Mukhtar" },
		{ lat = "31.930", long = "12.080", mark = "Location dot red.svg", marksize = "6", label = "[[Rajaban]]", label_size = "0" },
		{ lat = "32.548", long = "13.435", mark = "Dot green ff4.svg", marksize = "5", label = "[[Suq al Ahad]]", label_size = "0" },
        { lat = "32.783", long = "13.219", mark = "Dot green ff4.svg", marksize = "7", label = "[[Khallat al-Furjan]]", label_size = "0" },
        { lat = "32.764", long = "13.189", mark = "Dot green ff4.svg", marksize = "5", label = "[[Khallat al-Ghafar]]", label_size = "0" },
        { lat = "30.6506", long = "18.2688", mark = "Location dot red.svg", marksize = "5", label = "[[Wadi al-Khila]]", label_size = "0" },
        { lat = "33.148", long = "11.563", mark = "Dot green ff4.svg", marksize = "8", label = "[[Ras Ajdir|Ras Ajdir border crossing]]", label_size = "65", link = "Ras Ajdir", position = "top"},
        { lat = "30.6506", long = "18.2688", mark = "Location dot red.svg", marksize = "5", label = "[[Wadi al-Khila]]", link = "Wadi al-Khila", label_size = "0" },
        { lat = "31.4", long = "15.283", mark = "Dot green ff4.svg", marksize = "4", label = "[[Wadi Zamzam]]", link = "Wadi Zamzam", label_size = "0" },
		{ lat = "30.588", long = "18.415", mark = "Location dot red.svg", marksize = "10", label = "[[Ras Lanuf]]", label_size = "80", link = "Ras Lanuf", position = "right" },
		{ lat = "32.883", long = "22.183", mark = "Location dot red.svg", marksize = "8", label = "[[Ras Al Hilal]]", label_size = "0", link = "Ras Al Hilal" },
		{ lat = "32.794", long = "12.488", mark = "Dot green ff4.svg", marksize = "14", label = "[[Sabratha]]", label_size = "80", link = "Sabratha", position = "bottom" },
		{ lat = "32.756", long = "12.579", mark = "Dot green ff4.svg", marksize = "11", label = "[[Sorman]]", label_size = "0", link = "Sorman" },
		{ lat = "27.034", long = "14.422", mark = "Map-ctl2-red+lime.svg", marksize = "14", label = "[[Sabha, Libya|Sabha]]", label_size = "100", link = "Sabha", position = "right" },
		{ lat = "27.011", long = "14.454", mark = "Abm-red-icon.png", marksize = "8", label = "[[Sabha castle]]", label_size = "0" },
		{ lat = "32.828", long = "21.862", mark = "Location dot red.svg", marksize = "12", label = "[[Shahhat]]", label_size = "80", link = "Shahhat", position = "top" },
		{ lat = "31.205", long = "16.588", mark = "Location dot red.svg", marksize = "16", label = "[[Sirte]]", label_size = "90", link = "Sirte", position = "top" },
		{ lat = "32.615", long = "13.041", mark = "Dot green ff4.svg", marksize = "4", label = "[[as-Sa'adiyah]]", label_size = "0" },
		{ lat = "32.637", long = "13.072", mark = "Dot green ff4.svg", marksize = "4", label = "[[at-Tuwayshah]]", label_size = "0" },
		{ lat = "31.045", long = "16.658", mark = "Abm-red-icon.png", marksize = "6", label = "[[Maskar al-Sa'adi base HQ]]", label_size = "0" },
		{ lat = "32.672", long = "13.043", mark = "Abm-lime-icon.png", marksize = "5", label = "[[Farsiyah racetrack]]", label_size = "0" },
		{ lat = "32.6", long = "13.35", mark = "Abm-lime-icon.png", marksize = "6", label = "[[Sidi Al-Sayeh Recycling Factory]]", label_size = "0" },
		{ lat = "32.583", long = "13.456", mark = "Abm-lime-icon.png", marksize = "6", label = "[[Khaled Ibn al-Walid Brigade]]", label_size = "0" },
		{ lat = "27.275", long = "14.882", mark = "Location dot red.svg", marksize = "5", label = "[[Samnu]]", label_size = "0", link = "Samnu" },
		{ lat = "29.069", long = "15.783", mark = "Location dot red.svg", marksize = "8", label = "[[Sokna, Libya|Sokna]]", label_size = "70", link = "Sokna, Libya", position = "left" },
		{ lat = "31.096", long = "20.226", mark = "Location dot red.svg", marksize = "8", label = "[[Sultan, Libya|Sultan]]", label_size = "70", link = "Sultan", position = "left" },
		{ lat = "31.441", long = "20.153", mark = "Location dot red.svg", marksize = "6", label = "[[El Magrun |Magroun]]", label_size = "70", link = "Magroun", position = "right" },
		{ lat = "31.427", long = "20.032", mark = "Location dot red.svg", marksize = "6", label = "[[Kurkura (Carcura)]]", label_size = "0" },
		{ lat = "32.897", long = "21.963", mark = "Location dot red.svg", marksize = "8", label = "[[Susa]]", label_size = "0", link = "Susa, Libya" },
		{ lat = "31.669", long = "20.253", mark = "Location dot red.svg", marksize = "8", label = "[[Suluq]]", label_size = "80", link = "Suluq", position = "right" },
		{ lat = "32.480", long = "21.127", mark = "Location dot red.svg", marksize = "8", label = "[[Tacnis]]", label_size = "0", link = "Tacnis" },
		{ lat = "32.644", long = "13.139", mark = "Dot green ff4.svg", marksize = "4", label = "[[Sidrah]]", label_size = "0" },
		{ lat = "31.999", long = "15.053", mark = "Dot green ff4.svg", marksize = "10", label = "[[Tawergha]]", label_size = "80", link = "Tawergha", position = "top" },
		{ lat = "32.882", long = "13.351", mark = "Dot green ff4.svg", marksize = "12", label = "[[Tajura]]", label_size = "70", link = "Tajura", position = "right" },
		{ lat = "32.434", long = "13.634", mark = "Dot green ff4.svg", marksize = "9", label = "[[Tarhuna]]", label_size = "70", link = "Tarhuna", position = "top" },
		{ lat = "27.488", long = "13.126", mark = "Dot green ff4.svg", marksize = "5", label = "[[Tmissan]]", label_size = "0", link = "Tmissan" },
		{ lat = "32.456", long = "13.909", mark = "Dot green ff4.svg", marksize = "5", label = "[[Dawun]]", label_size = "0", link = "Dawun" },
		{ lat = "32.444", long = "13.767", mark = "Dot green ff4.svg", marksize = "4", label = "[[Al Khadra]]", label_size = "0", link = "Al Khadra" },
		{ lat = "31.393", long = "13.741", mark = "Dot green ff4.svg", marksize = "6", label = "[[Tininay]]", label_size = "0" },
		{ lat = "32.745", long = "13.715", mark = "Dot green ff4.svg", marksize = "11", label = "[[Castelverde, Libya|Garabulli]]", label_size = "70", link = "Castelverde, Libya", position = "top" },
		{ lat = "32.567", long = "13.173", mark = "Dot green ff4.svg", marksize = "5", label = "[[Al Majadib]]", label_size = "0" },
		{ lat = "32.298", long = "13.274", mark = "Dot green ff4.svg", marksize = "6", label = "[[al-Jawarniyah]]", label_size = "0" },
		{ lat = "32.335", long = "13.4805", mark = "Dot green ff4.svg", marksize = "5", label = "[[Sidi as Sayd]]", label_size = "0" },
		{ lat = "32.444", long = "13.367", mark = "Dot green ff4.svg", marksize = "4", label = "[[Fam Mullaga]]", label_size = "0" },
		{ lat = "32.526", long = "13.205", mark = "Dot green ff4.svg", marksize = "3", label = "[[Sog Al-Khmies Emsihel]]", label_size = "0" },
		{ lat = "32.539", long = "13.173", mark = "Dot green ff4.svg", marksize = "5", label = "[[Asbiya]]", label_size = "0" },
		{ lat = "32.709", long = "13.965", mark = "Dot green ff4.svg", marksize = "4", label = "[[al ‘Allus]]", label_size = "0" },
		{ lat = "32.414", long = "14.793", mark = "Dot green ff4.svg", marksize = "4", label = "[[Ad Dafinah]]", label_size = "0" },
		{ lat = "31.937", long = "20.081", mark = "Location dot red.svg", marksize = "6", label = "[[Tika]]", label_size = "0", link = "Tika" },
		{ lat = "31.959", long = "20.050", mark = "Location dot red.svg", marksize = "6", label = "[[Tika Housing Units]]", label_size = "0" },
		{ lat = "32.532", long = "20.572", mark = "Location dot red.svg", marksize = "10", label = "[[Tocra]]", label_size = "80", link = "Tocra", position = "top" },
		{ lat = "32.078", long = "23.959", mark = "Location dot red.svg", marksize = "16", label = "[[Tobruk#Libyan Civil Wars|Tobruk]]", label_size = "100", link = "Tobruk#Libyan Civil Wars", position = "top" },
		{ lat = "32.705", long = "20.945", mark = "Location dot red.svg", marksize = "8", label = "[[Tolmeitha]]", label_size = "0", link = "Tolmeitha" },
		{ lat = "25.923", long = "14.421", mark = "Location dot red.svg", marksize = "8", label = "[[Traghan]]", label_size = "70", link = "Traghan", position = "bottom" },
		{ lat = "29.982", long = "14.259", mark = "Dot green ff4.svg", marksize = "8", label = "[[As Shwayrif]]", label_size = "0", link = "As Shwayrif" },
		{ lat = "25.664", long = "21.045", mark = "Location dot red.svg", marksize = "8", label = "[[Tazirbu]]", label_size = "80", link = "Tazirbu", position = "left" },
		{ lat = "32.887", long = "13.192", mark = "Dot green ff4.svg", marksize = "32", label = "[[Tripoli#Libyan civil war|Tripoli]]", label_size = "140", link = "Tripoli#Libyan civil war", position = "top" },
		{ lat = "22.647", long = "14.200", mark = "Location dot red.svg", marksize = "8", label = "[[Tumu, Libya|Tumu border checkpoint]]", label_size = "70", link = "Tumu, Libya", position = "bottom"},
		{ lat = "24.713", long = "10.206", mark = "Dot_green_ff4.svg", marksize = "8", label = "[[Tin El Koum|Aysayn border crossing]]", label_size = "70", link = "Tin El Koum", position = "bottom"},
		{ lat = "26.587", long = "12.766", mark = "Dot green ff4.svg", marksize = "11", label = "[[Ubari]]", label_size = "80", link = "Ubari", position = "top" },
		{ lat = "32.534", long = "23.007", mark = "Location dot red.svg", marksize = "10", label = "[[Umm al Rizam]]", label_size = "80", link = "Umm al Rizam", position = "right" },
		{ lat = "32.336", long = "23.059", mark = "Location dot red.svg", marksize = "8", label = "[[Tmimi]]", label_size = "0", link = "Umm al Aranib" },
		{ lat = "26.159", long = "14.690", mark = "Location dot red.svg", marksize = "4", label = "[[Tuwaywa]]", label_size = "0", link = "Umm al Aranib" },
		{ lat = "24.334", long = "14.266", mark = "Location dot red.svg", marksize = "6", label = "[[Tajarhi]]", label_size = "70", link = "Tajarhi", position = "top" },
		{ lat = "31.842", long = "12.972", mark = "Dot green ff4.svg", marksize = "6", label = "[[Tabunaini]]", label_size = "0", link = "Tabunaini" },
		{ lat = "32.207", long = "13.042", mark = "Dot green ff4.svg", marksize = "6", label = "[[Qawasim]]", label_size = "0", link = "Qawasim" },
		{ lat = "24.919", long = "14.6", mark = "Location dot red.svg", marksize = "4", label = "[[Qasr Massaud]]", label_size = "0", link = "Qasr Massaud" },
		{ lat = "24.831", long = "14.499", mark = "Location dot red.svg", marksize = "5", label = "[[Al-Bakhi]]", label_size = "0", link = "Al-Bakhi" },
		{ lat = "24.779", long = "14.499", mark = "Location dot red.svg", marksize = "5", label = "[[Madrusah]]", label_size = "0", link = "Madrusah" },
		{ lat = "25.872", long = "14.381", mark = "Location dot red.svg", marksize = "4", label = "[[Bin Dlif]]", label_size = "0", link = "Bin Dlif" },
		{ lat = "25.854", long = "14.279", mark = "Location dot red.svg", marksize = "4", label = "[[Al Bedan]]", label_size = "0", link = "Al Bedan" },
		{ lat = "25.858", long = "14.471", mark = "Location dot red.svg", marksize = "4", label = "[[Maifen]]", label_size = "0", link = "Maifen" },
		{ lat = "26.163", long = "14.716", mark = "Location dot red.svg", marksize = "4", label = "[[Misquwin]]", label_size = "0", link = "Umm al Aranib" },
		{ lat = "26.114", long = "14.809", mark = "Location dot red.svg", marksize = "4", label = "[[Al Hummayrah]]", label_size = "0", link = "Umm al Aranib" },
		{ lat = "25.904", long = "14.566", mark = "Location dot red.svg", marksize = "5", label = "[[Az Zaytunah]]", label_size = "0", link = "Umm al Aranib" },
		{ lat = "25.944", long = "14.647", mark = "Location dot red.svg", marksize = "4", label = "[[Maghwah]]", label_size = "0", link = "Umm al Aranib" },
		{ lat = "26.159", long = "14.848", mark = "Location dot red.svg", marksize = "4", label = "[[Al Budayr]]", label_size = "0", link = "Umm al Aranib" },
		{ lat = "26.127", long = "14.744", mark = "Location dot red.svg", marksize = "7", label = "[[Murzuq District|Umm al Aranib]]", label_size = "70", link = "Murzuq District", position = "top" },
		{ lat = "29.161", long = "16.140", mark = "Location dot red.svg", marksize = "10", label = "[[Waddan, Libya|Waddan]]", label_size = "90", link = "Waddan, Libya", position = "right" },
		{ lat = "31.367", long = "15.227", mark = "Dot green ff4.svg", marksize = "6", label = "[[Al Qaddahiyah|Gheddahia]]", label_size = "80", link = "Al Qaddahiyah", position = "bottom" },
		{ lat = "31.171", long = "15.089", mark = "Dot green ff4.svg", marksize = "6", label = "[[#Wadi Zamzam|Al-Fukhiyah]]", label_size = "0" },
		{ lat = "30.893", long = "17.575", mark = "Location dot red.svg", marksize = "5", label = "[[Wadi Ahmar]]", label_size = "0" },
		{ lat = "31.980", long = "10.684", mark = "Dot green ff4.svg", marksize = "8", label = "[[Wazzin|Wazzin Border Crossing]]", label_size = "70", link = "Wazzin", position = "top"},
		{ lat = "31.942", long = "10.665", mark = "Dot green ff4.svg", marksize = "7", label = "[[Wazzin]]", label_size = "80", link = "Wazzin", position = "left"},
		{ lat = "31.647", long = "12.696", mark = "Dot green ff4.svg", marksize = "6", label = "[[Wamis]]", label_size = "0", link = "Wamis" },
		{ lat = "31.632", long = "12.756", mark = "Dot green ff4.svg", marksize = "6", label = "[[Al Wasta]]", label_size = "0", link = "Al Wasta" },
		{ lat = "27.482", long = "13.331", mark = "Location dot red.svg", marksize = "5", label = "[[Wanzarik]]", label_size = "0", link = "Wanzariks" },
		{ lat = "32.063", long = "12.527", mark = "Dot green ff4.svg", marksize = "12", label = "[[Yafran]]", label_size = "70", link = "Yafran", position = "bottom" },
		{ lat = "32.950", long = "11.866", mark = "Dot green ff4.svg", marksize = "10", label = "[[Zaltan]]", label_size = "80", link = "Zaltan", position = "left" },
		{ lat = "32.707", long = "13.477", mark = "Dot green ff4.svg", marksize = "5", label = "[[Zatarna]]", label_size = "0" },
		{ lat = "32.69", long = "13.555", mark = "Dot green ff4.svg", marksize = "5", label = "[[Az Ziyanah]]", label_size = "0" },
		{ lat = "32.639", long = "13.575", mark = "Dot green ff4.svg", marksize = "5", label = "[[Al Khawaliq]]", label_size = "0" },
		{ lat = "32.785", long = "13.5", mark = "Dot green ff4.svg", marksize = "6", label = "[[an-Nashiya']]", label_size = "0" },
		{ lat = "32.808", long = "13.453", mark = "Dot green ff4.svg", marksize = "5", label = "[[Khallet al Kawateb]]", label_size = "0" },
		{ lat = "28.549", long = "17.551", mark = "Location dot red.svg", marksize = "8", label = "[[Zella, Libya|Zella]]", label_size = "80", link = "Zella, Libya", position = "top" },
		{ lat = "31.907", long = "12.255", mark = "Location dot red.svg", marksize = "10", label = "[[Zintan]]", label_size = "80", link = "Zintan", position = "bottom" },
		{ lat = "32.937", long = "12.086", mark = "Dot green ff4.svg", marksize = "11", label = "[[Zuwarah]]", label_size = "90", link = "Zuwarah", position = "top" },
		{ lat = "26.162", long = "15.125", mark = "Location dot red.svg", marksize = "8", label = "[[Zwila]]", label_size = "70", link = "Zwila", position = "right" },
		{ lat = "26.395", long = "15.785", mark = "Location dot red.svg", marksize = "7", label = "[[Tmassa]]", label_size = "80", link = "Tmassa", position = "top" },
		{ lat = "26.087", long = "13.508", mark = "Location dot red.svg", marksize = "6", label = "[[Tasawah]]", label_size = "0", link = "Tasawah" },
		{ lat = "25.966", long = "14.25", mark = "Location dot red.svg", marksize = "6", label = "[[Funqul]]", label_size = "70", link = "Funqul", position = "top" },
		{ lat = "26.02", long = "15.165", mark = "Location dot red.svg", marksize = "5", label = "[[Tarbu]]", label_size = "0" },
		{ lat = "25.9", long = "14.166", mark = "Location dot red.svg", marksize = "5", label = "[[Zizau]]", label_size = "0", link = "Zizau", position = "top" },
		{ lat = "25.933", long = "14.1", mark = "Location dot red.svg", marksize = "5", label = "[[Qawat]]", label_size = "0", link = "Qawat", position = "top" },
		{ lat = "33.0630", long = "11.8168", mark = "Abm-lime-icon.png", marksize = "6", label = "[[Abou Kemash complex for Chemical Industries (GCCI)]]", label_size = "0" },
		{ lat = "30.952", long = "20.120", mark = "Location dot red.svg", marksize = "10", label = "[[Zuwetina]]", label_size = "90", link = "Zuwetina", position = "left" },		
		{ lat = "32.481", long = "14.551", mark = "Dot green ff4.svg", marksize = "18", label = "[[Zliten]]", label_size = "100", link = "Zliten", position = "top" },
		{ lat = "32.108", long = "13.022", mark = "Dot green ff4.svg", marksize = "5", label = "[[Az Zuwayyah]]", label_size = "0", link = "Az Zuwayyah" },
		{ lat = "32.128", long = "12.945", mark = "Dot green ff4.svg", marksize = "5", label = "[[Al Ya‘aqīb]]", label_size = "0", link = "Al Ya‘aqīb" },
		{ lat = "32.047", long = "13.004", mark = "Dot green ff4.svg", marksize = "5", label = "[[Al Kulaybah]]", label_size = "0", link = "Al Kulaybah" },
		{ lat = "31.973", long = "13.2", mark = "Dot green ff4.svg", marksize = "4", label = "[[Ghawt ar Rih]]", label_size = "0", link = "Ghawt ar Rih" },
		{ lat = "32.065", long = "13.048", mark = "Dot green ff4.svg", marksize = "5", label = "[[Abu Ma`ad]]", label_size = "0", link = "Abu Ma`ad" },
		{ lat = "31.916", long = "24.700", mark = "Location dot red.svg", marksize = "8", label = "[[Bi`r al Ashhab]]", label_size = "0", link = "Bi`r_al_Ashhab" },
		{ lat = "32.127", long = "13.1", mark = "Dot green ff4.svg", marksize = "5", label = "[[As Salahat]]", label_size = "0" },
		{ lat = "32.143", long = "13.106", mark = "Dot green ff4.svg", marksize = "5", label = "[[al Kamshat]]", label_size = "0" },
		{ lat = "32.356", long = "13.047", mark = "Dot green ff4.svg", marksize = "6", label = "[[Al Hira]]", label_size = "0" },
		{ lat = "32.324", long = "13.043", mark = "Abm-lime-icon.png", marksize = "5", label = "[[Al-Hira Gate]]", label_size = "0" },
		{ lat = "27.064", long = "14.454", mark = "Abm-red-icon.png", marksize = "7", label = "[[Sebha Ammunition Depot]]", label_size = "0" },
		{ lat = "31.944", long = "12.988", mark = "Abm-lime-icon.png", marksize = "5", label = "[[Quadama]]", label_size = "0" },
		{ lat = "32.775", long = "13.205", mark = "Abm-lime-icon.png", marksize = "6", label = "[[Yarmouk Camp]]", label_size = "0" },
		{ lat = "32.763", long = "13.2", mark = "Abm-lime-icon.png", marksize = "5", label = "[[Artillery Camp]]", label_size = "0" },
		{ lat = "32.815", long = "13.296", mark = "Abm-lime-icon.png", marksize = "6", label = "[[42nd Battalion]]", label_size = "0" },
		{ lat = "32.622", long = "13.122", mark = "Abm-lime-icon.png", marksize = "6", label = "[[Air Defense Camp(SA-2 Missile Battery)]]", label_size = "0" },
		{ lat = "32.608", long = "13.085", mark = "Abm-lime-icon.png", marksize = "5", label = "[[Air Defense Camp(SA-5 Missile Battery)]]", label_size = "0" },
		{ lat = "32.677", long = "13.056", mark = "Abm-lime-icon.png", marksize = "5", label = "[[Al Zahra Bridge]]", label_size = "0" },
		{ lat = "32.504", long = "12.984", mark = "Abm-lime-icon.png", marksize = "7", label = "[[4th Brigade Base]]", label_size = "0" },
		{ lat = "32.799", long = "12.913", mark = "Abm-lime-icon.png", marksize = "5", label = "[[Highway Junction Bridge 27th gate]]", label_size = "0" },
		{ lat = "32.765", long = "13.144", mark = "Abm-lime-icon.png", marksize = "5", label = "[[Equestrian bridge]]", label_size = "0" },
		{ lat = "32.733", long = "13.148", mark = "Abm-lime-icon.png", marksize = "5", label = "[[Transport Camp]]", label_size = "0" },
		{ lat = "31.802", long = "10.974", mark = "Abm-lime-icon.png", marksize = "7", label = "[[Al-Juwaybiyah military base]]", label_size = "0" },
		--{ lat = "", long = "", mark = "Location dot red.svg", marksize = "14", label = "[[]]", label_size = "140", link = "", position = "left" },
		
		--Airbases
		{ lat = "32.669", long = "13.148", mark = "Fighter-jet-lime-icon.svg", marksize = "11", label = "[[Tripoli International Airport]]", link = "Tripoli International Airport", label_size = "0" },
		{ lat = "32.896", long = "13.285", mark = "Fighter-jet-lime-icon.svg", marksize = "11", label = "[[Mitiga International Airport]]", link = "Mitiga International Airport", label_size = "0" },
		{ lat = "32.100", long = "20.374", mark = "Fighter-jet-red-icon.svg", marksize = "11", label = "[[Benina International Airport]]", link = "Benina International Airport", label_size = "0" },
		{ lat = "31.950", long = "23.910", mark = "Fighter-jet-red-icon.svg", marksize = "11", label = "[[Tobruk International Airport]]", link = "Tobruk Airport", label_size = "0" },
		{ lat = "21.688", long = "21.831", mark = "Fighter-jet-red-icon.svg", marksize = "11", label = "[[Maaten al-Sarra Air Base]]", link = "Maaten al-Sarra Air Base", label_size = "0" },
		{ lat = "32.326", long = "14.960", mark = "Fighter-jet-lime-icon.svg", marksize = "11", label = "[[Misrata International Airport]]", link = "Misrata International Airport", label_size = "0" },
		{ lat = "31.063", long = "16.595", mark = "Fighter-jet-red-icon.svg", marksize = "11", label = "[[Ghardabiya Airbase]]", link = "Ghardabiya Airbase", label_size = "0" },
		{ lat = "30.151", long = "9.700", mark = "Fighter-jet-lime-icon.svg", marksize = "11", label = "[[Ghadames Airport]]", link = "Ghadames Airport", label_size = "0" },
		{ lat = "26.856", long = "14.469", mark = "Fighter-jet-red-icon.svg", marksize = "11", label = "[[Sabha Airbase]]", link = "Sabha Airbase", label_size = "0" },
		{ lat = "27.233", long = "14.651", mark = "Fighter-jet-red-icon.svg", marksize = "11", label = "[[Taminhint Airbase]]", link = "Taminhint Airbase", label_size = "0" },
		{ lat = "32.789", long = "21.964", mark = "Fighter-jet-red-icon.svg", marksize = "11", label = "[[Al Abraq International Airport]]", link = "Al Abraq International Airport", label_size = "0" },
		{ lat = "31.860", long = "23.906", mark = "Fighter-jet-red-icon.svg", marksize = "11", label = "[[Gamal Abdul El Nasser Airbase]]", link = "Gamal Abdul El Nasser Airbase", label_size = "0" },
		{ lat = "25.146", long = "10.143", mark = "Fighter-jet-lime-icon.svg", marksize = "11", label = "[[Ghat Airport]]", link = "Ghat Airport", label_size = "0" },
		{ lat = "29.204", long = "16.001", mark = "Fighter-jet-red-icon.svg", marksize = "11", label = "[[Al Jufra Airbase]]", link = "Al Jufra Airbase", label_size = "0" },
		{ lat = "32.538", long = "22.759", mark = "Fighter-jet-red-icon.svg", marksize = "11", label = "[[Martuba Airbase]]", link = "Martuba Airbase", label_size = "0" },
		{ lat = "31.705", long = "14.912", mark = "Fighter-jet-lime-icon.svg", marksize = "11", label = "[[Nanur Airport]]", link = "Nanur Airport", label_size = "0" },
		{ lat = "30.702", long = "12.484", mark = "Fighter-jet-lime-icon.svg", marksize = "11", label = "[[Habit Awlad Muhammad Airport]]", link = "Habit Awlad Muhammad Airport", label_size = "0" },
		{ lat = "32.482", long = "11.892", mark = "Fighter-jet-lime-icon.svg", marksize = "11", label = "[[al-Watya Airbase]]", link = "al-Watya Airbase", label_size = "0" },
		{ lat = "32.528", long = "11.876", mark = "Abm-lime-icon.png", marksize = "7", label = "[[Radar station (Okba Ibn Nafa)]]", label_size = "0" },
		{ lat = "32.743", long = "22.134", mark = "Abm-red-icon.png", marksize = "7", label = "[[Lamluda army training center]]", link = "Lamluda army training center", label_size = "0" },
		{ lat = "30.379", long = "19.579", mark = "Fighter-jet-red-icon.svg", marksize = "11", label = "[[Marsa el Brega Airport ]]", link = "Marsa el Brega Airport ", label_size = "0" },
		{ lat = "30.500", long = "18.527", mark = "Fighter-jet-red-icon.svg", marksize = "11", label = "[[Ras Lanuf Airport]]", link = "Ras Lanuf Airport", label_size = "0" },
		{ lat = "29.110", long = "15.965", mark = "Fighter-jet-red-icon.svg", marksize = "11", label = "[[Hun Airport]]", link = "Hun Airport", label_size = "0" },
		{ lat = "26.568", long = "12.833", mark = "Fighter-jet-lime-icon.svg", marksize = "11", label = "[[Ubari Airport]]", link = "Ubari Airport", label_size = "0" },
		{ lat = "26.539", long = "12.771", mark = "Map-peak-lime.svg", marksize = "9", label = "[[Tendi mountain]]", link = "Tendi mountain", label_size = "0" },
		{ lat = "32.475", long = "13.903", mark = "Map-peak-lime.svg", marksize = "8", label = "[[Ra’s at Tulaylah]]", link = "Ra’s at Tulaylah", label_size = "0" },
                       { lat = "32.488", long = "13.868", mark = "Map-peak-lime.svg", marksize = "8", label = "[[Ra’s al Karmah]]", link = "Ra’s al Karmah", label_size = "0" },
                       { lat = "32.489", long = "13.905", mark = "Map-peak-lime.svg", marksize = "8", label = "[[Ra’s Manana]]", link = "Ra’s Manana", label_size = "0" },
		{ lat = "27.683", long = "14.217", mark = "Fighter-jet-lime-icon.svg", marksize = "11", label = "[[Brak Airport]]", link = "Brak Airport", label_size = "0" },
		{ lat = "32.9530", long = "12.0156", mark = "Fighter-jet-lime-icon.svg", marksize = "11", label = "[[Zuwara Airport]]", link = "Zuwara Airport", label_size = "0" },
		{ lat = "29.139", long = "16.160", mark = "Fighter-jet-red-icon.svg", marksize = "11", label = "[[Waddan Airport]]", link = "Waddan Airport", label_size = "0" },
		{ lat = "24.200", long = "23.38", mark = "Fighter-jet-red-icon.svg", marksize = "11", label = "[[Kufra Airport]]", link = "Kufra Airport", label_size = "0" },
		{ lat = "32.789", long = "21.964", mark = "Fighter-jet-red-icon.svg", marksize = "11", label = "[[Al Abraq International Airport]]", link = "Al Abraq International Airport", label_size = "0" },
		{ lat = "31.732", long = "13.95", mark = "Fighter-jet-lime-icon.svg", marksize = "11", label = "[[Bani Walid Airport]]", link = "Bani Walid Airport", label_size = "0" },
		{ lat = "26.540", long = "12.235", mark = "Fighter-jet-lime-icon.svg", marksize = "9", label = "[[Al Sharara Airstrip]]", label_size = "0" },
		{ lat = "31.941", long = "13.157", mark = "Fighter-jet-lime-icon.svg", marksize = "9", label = "[[Airstrip]]", label_size = "0" },
		{ lat = "26.037", long = "12.045", mark = "Fighter-jet-lime-icon.svg", marksize = "9", label = "[[El Feel Airstrip]]", label_size = "0" },
		{ lat = "32.454", long = "23.119", mark = "Fighter-jet-red-icon.svg", marksize = "11", label = "[[Al Bumbah Airbase]]", label_size = "0" },
		{ lat = "25.368", long = "16.798", mark = "Fighter-jet-red-icon.svg", marksize = "11", label = "[[Waw Al Kabir Airport]]", label_size = "0" },
		{ lat = "24.182", long = "14.542", mark = "Fighter-jet-red-icon.svg", marksize = "11", label = "[[Al Wigh Air Base]]", link = "Al Wigh", label_size = "0" },
		
		--Industrial complexes and oil fields
		{ lat = "29.25", long = "19.666", mark = "Gota01.svg", marksize = "10", label = "[[Abu Lahib Oil Field]]", link = "Abu Lahib, Libya", label_size = "0" },
        { lat = "29.000", long = "19.833", mark = "Gota01.svg", marksize = "10", label = "[[Ain Jarbi Oil Field]]", link = "Ain Jarbi", label_size = "0" },
        { lat = "28.913", long = "10.049", mark = "Gota02.svg", marksize = "10", label = "[[Al Wafa Oil Field]]", link = "Al Wafa Oil Field", label_size = "0" },
		{ lat = "28.350", long = "18.967", mark = "Gota01.svg", marksize = "10", label = "[[Al Bayda Oil Field]]", link = "Al Bayda", label_size = "0" },
		{ lat = "30.083", long = "18.333", mark = "Gota01.svg", marksize = "10", label = "[[Al Bazuzi Oil Field]]", link = "Al Bazuzi", label_size = "0" },	
        { lat = "28.968", long = "17.465", mark = "Gota01.svg", marksize = "10", label = "[[Al Ghani Oil Field]]", link = "Al Ghani Oil Field", label_size = "0" },
		{ lat = "29.500", long = "12.950", mark = "Gota02.svg", marksize = "10", label = "[[Al Hammadah/al Hamra Oil Field]]", link = "Al Hammadah al Hamra", label_size = "0" },
		{ lat = "29.167", long = "18.083", mark = "Gota01.svg", marksize = "10", label = "[[Al Hufrah Oil Field]]", link = "Al Hufrah", label_size = "0" },
		{ lat = "28.224", long = "18.115", mark = "Gota01.svg", marksize = "10", label = "[[Al Sabah Oil Field]]", link = "Al Sabah", label_size = "0" },
		{ lat = "28.169", long = "19.148", mark = "Gota01.svg", marksize = "10", label = "[[Al Samah Oil Field]]", link = "Al Samah", label_size = "0" },
		{ lat = "29.416", long = "21.166", mark = "Gota01.svg", marksize = "10", label = "[[Amal Oil Field]]", link = "Amal Oil Field", label_size = "0" },
		{ lat = "28.966", long = "19.033", mark = "Gota01.svg", marksize = "10", label = "[[Ar Raqubah Oil Field]]", link = "Ar Raqubah", label_size = "0" },
		{ lat = "29.416", long = "19.750", mark = "Gota01.svg", marksize = "10", label = "[[Arshad Oil Field]]", link = "Arshad Oil Field", label_size = "0" },
		{ lat = "29.133", long = "21.450", mark = "Gota01.svg", marksize = "10", label = "[[Augila Oil Field/Awjilah Oil Field]]", link = "Augila", label_size = "0" },
		{ lat = "29.283", long = "17.800", mark = "Gota01.svg", marksize = "10", label = "[[Az Zahrah Oil Field]]", link = "Az Zahrah", label_size = "0" },
		{ lat = "28.666", long = "18.250", mark = "Gota01.svg", marksize = "10", label = "[[Az Zawwam Oil Field]]", link = "Az Zawwam", label_size = "0" },
		{ lat = "28.250", long = "19.250", mark = "Gota01.svg", marksize = "10", label = "[[Balat Oil Field]]", link = "Balat", label_size = "0" },	
        { lat = "29.75", long = "17.666", mark = "Gota01.svg", marksize = "10", label = "[[Bahi Oil Field]]", link = "Bahi", label_size = "0" },
		{ lat = "30.083", long = "18.333", mark = "Gota01.svg", marksize = "10", label = "[[Bazuzi Oil Field]]", link = "Bazuzi", label_size = "0" },
		{ lat = "28.350", long = "18.966", mark = "Gota01.svg", marksize = "10", label = "[[Beda Oil Field]]", link = "Beda", label_size = "0" },
		{ lat = "31.250", long = "12.066", mark = "Gota02.svg", marksize = "10", label = "[[Bir Tlakshin Oil Field]]", link = "Bir Tlakshin", label_size = "0" },
		{ lat = "27.500", long = "22.500", mark = "Gota01.svg", marksize = "10", label = "[[C-65 Oil Field]]", label_size = "0" },
		{ lat = "27.000", long = "20.000", mark = "Gota01.svg", marksize = "10", label = "[[Defa Oil Field]]", link = "Defa", label_size = "0" },
		{ lat = "29.500", long = "17.833", mark = "Gota01.svg", marksize = "10", label = "[[Dahra Oil Field]]", link = "Dahra", label_size = "0" },
		{ lat = "28.550", long = "18.683", mark = "Gota01.svg", marksize = "10", label = "[[Dur Oil Field]]", link = "Dur Oil Field", label_size = "0" },
		{ lat = "29.000", long = "19.833", mark = "Gota01.svg", marksize = "10", label = "[[Ein Jerbi Oil Field]]", link = "Ein Jerbi", label_size = "0" },
		{ lat = "26.578", long = "12.212", mark = "Gota01.svg", marksize = "12", label = "[[El Sharara Oil Field]]", link = "El_Sharara_oil_field", label_size = "0" },
		{ lat = "29.416", long = "21.166", mark = "Gota01.svg", marksize = "10", label = "[[El-Amal B-l Oil Field]]", link = "El-Amal B-l", label_size = "0" },
		{ lat = "26.027", long = "11.975", mark = "Gota02.svg", marksize = "10", label = "[[El-Feel Oil Field]]", link = "El-Feel", label_size = "0" },
		{ lat = "29.416", long = "13.000", mark = "Gota02.svg", marksize = "10", label = "[[Emgayet Oil Field]]", link = "Emgayet", label_size = "0" },
		{ lat = "27.591", long = "18.486", mark = "Gota01.svg", marksize = "10", label = "[[En-naga Oil Field]]", link = "En-naga", label_size = "0" },
		{ lat = "29.500", long = "17.333", mark = "Gota01.svg", marksize = "10", label = "[[Facha Oil Field]]", link = "Facha", label_size = "0" },
		{ lat = "29.250", long = "18.083", mark = "Gota01.svg", marksize = "10", label = "[[Farroud Oil Field]]", link = "Farroud", label_size = "0" },
		{ lat = "28.833", long = "18.833", mark = "Gota01.svg", marksize = "10", label = "[[Haram Oil Field]]", link = "Haram", label_size = "0" },
		{ lat = "28.500", long = "20.666", mark = "Gota01.svg", marksize = "10", label = "[[Harash Oil Field]]", link = "Harash", label_size = "0" },
		{ lat = "29.166", long = "18.083", mark = "Gota01.svg", marksize = "10", label = "[[Hofra Oil Field]]", link = "Hofra", label_size = "0" },
		{ lat = "28.833", long = "20.833", mark = "Gota01.svg", marksize = "10", label = "[[Idris/Intisar Oil Fields]]", label_size = "0" },
		{ lat = "29.033", long = "21.343", mark = "Gota01.svg", marksize = "10", label = "[[Jalu Oil Field]]", link = "Jalu", label_size = "0" },
		{ lat = "28.116", long = "18.700", mark = "Gota01.svg", marksize = "10", label = "[[Khalifah Oil Field]]", link = "Khalifah Oil Field", label_size = "0" },
		{ lat = "28.383", long = "18.716", mark = "Gota01.svg", marksize = "10", label = "[[Khuff Oil Field]]", link = "Khuff", label_size = "0" },
		{ lat = "28.750", long = "18.500", mark = "Gota01.svg", marksize = "10", label = "[[Kohtla Oil Field]]", link = "Kohtla", label_size = "0" },
		{ lat = "29.250", long = "19.666", mark = "Gota01.svg", marksize = "10", label = "[[Lehib Oil Field]]", link = "Lehib", label_size = "0" },
		{ lat = "30.000", long = "17.250", mark = "Gota01.svg", marksize = "10", label = "[[Mabruk Oil Field]]", link = "Mabruk", label_size = "0" },
        { lat = "28.500", long = "21.750", mark = "Gota01.svg", marksize = "10", label = "[[Magid Oil Field]]", label_size = "0" },
		{ lat = "29.200", long = "21.383", mark = "Gota01.svg", marksize = "10", label = "[[Nafurah Oil Field]]", link = "Nafurah", label_size = "0" },
		{ lat = "28.333", long = "19.500", mark = "Gota01.svg", marksize = "10", label = "[[#Ora|Ora Oil Field]]", label_size = "0" },
		{ lat = "29.200", long = "21.783", mark = "Gota01.svg", marksize = "10", label = "[[Qitmir Oil Field]]", link = "Qitmir", label_size = "0" },
		{ lat = "28.966", long = "19.033", mark = "Gota01.svg", marksize = "10", label = "[[Raguba Oil Field]]", link = "Raguba field", label_size = "0" },
		{ lat = "29.500", long = "17.333", mark = "Gota01.svg", marksize = "10", label = "[[Sacha Oil Field]]", link = "Sacha", label_size = "0" },
		{ lat = "28.000", long = "19.500", mark = "Gota01.svg", marksize = "10", label = "[[Samah Oil Field]]", link = "Samah", label_size = "0" },
		{ lat = "28.220", long = "19.130", mark = "Gota01.svg", marksize = "10", label = "[[Sarir Oil Field]]", link = "Sarir_field", label_size = "0" },
		{ lat = "28.100", long = "20.000", mark = "Gota01.svg", marksize = "10", label = "[[Waha Oil Field]]", link = "Waha_field", label_size = "0" },
		{ lat = "28.916", long = "19.770", mark = "Gota01.svg", marksize = "10", label = "[[Zelten oil Field]]", link = "Zelten_Oil_Field", label_size = "0" },
		{ lat = "28.580", long = "17.330", mark = "Gota01.svg", marksize = "10", label = "[[Zella Oil Field]]", link = "Zella Oil Field", label_size = "0" },
		{ lat = "28.666", long = "18.250", mark = "Gota01.svg", marksize = "10", label = "[[Zauam Oil Field]]", link = "Zauam", label_size = "0" },
		{ lat = "28.333", long = "19.500", mark = "Gota01.svg", marksize = "10", label = "[[`Awra Oil Field]]", link = "`Awra", label_size = "0" },
		{ lat = "29.000", long = "19.833", mark = "Gota01.svg", marksize = "10", label = "[[`Ayn Jarbi Oil Field]]", link = "`Ayn Jarbi", label_size = "0" },
		{ lat = "28.913", long = "10.049", mark = "Gota02.svg", marksize = "10", label = "[[Al Wafa Oil Field]]", link = "Al Wafa Oil Field", label_size = "0" },
        { lat = "30.629", long = "18.350", mark = "Location dot red.svg", marksize = "8", label = "[[Sidra, Libya|Sidra]]", link = "Sidra, Libya", label_size = "75", position = "top" },
		{ lat = "30.608", long = "18.283", mark = "Gota01.svg", marksize = "6", label = "[[Sidra Oil Tanks]]", link = "Sidra Oil Tanks", label_size = "0" },
		{ lat = "30.474", long = "18.575", mark = "Gota01.svg", marksize = "10", label = "[[Ras Lanuf Petroleum Complex]]", link = "Ras Lanuf Petroleum Complex", label_size = "0" },
		{ lat = "32.066", long = "23.983", mark = "Anchor pictogram red.svg", marksize = "11", label = "[[Hariga oil port/Terminal]]", link = "Hariga oil port/Terminal", label_size = "0" },
		{ lat = "30.916", long = "20.083", mark = "Anchor pictogram red.svg", marksize = "11", label = "[[Zuwetina oil port/Terminal]]", link = "Zuwetina oil port/Terminal", label_size = "0" },
        { lat = "31.217", long = "16.346", mark = "Icon NuclearPowerPlant-red.svg", marksize = "7", label = "[[Al-Khalej Power Plant]]", label_size = "0" },
        { lat = "32.855", long = "12.238", mark = "Icon NuclearPowerPlant-green.svg", marksize = "8", label = "[[Mellitah Oil & Gas Company]]", link = "Mellitah", label_size = "0" },
        { lat = "32.782", long = "12.693", mark = "Icon NuclearPowerPlant-green.svg", marksize = "8", label = "[[Zawiyah Oil Refinery]]", link = "Zawiyah", label_size = "0" },
        { lat = "32.84", long = "13.453", mark = "Icon NuclearPowerPlant-green.svg", marksize = "6", label = "[[Nuclear Research Center]]", link = "Nuclear Research Center", label_size = "0" },
        { lat = "31.147", long = "16.828", mark = "BSicon STRrf red.svg", marksize = "12", label = "[[Ghardabiya Reservoir 1]]", label_size = "0" },
        { lat = "31.114", long = "16.665", mark = "BSicon STRrf red.svg", marksize = "12", label = "[[Ghardabiya Reservoir 2]]", label_size = "0" },
        { lat = "32.055", long = "20.183", mark = "Icon NuclearPowerPlant-red.svg", marksize = "5", label = "[[Benghazi Cement Factory]]", label_size = "0" },
		--Naval bases
		{ lat = "32.906", long = "13.220", mark = "Anchor pictogram green.svg", marksize = "12", label = "[[Tripoli Naval Base]]", link = "Tripoli Naval Base", label_size = "0" },
		{ lat = "32.684", long = "14.236", mark = "Anchor pictogram green.svg", marksize = "11", label = "[[Khoms Naval Base]]", link = "khoms Naval Base", label_size = "0" },
		{ lat = "32.763", long = "22.658", mark = "Anchor pictogram red.svg", marksize = "12", label = "[[Derna Sea Port]]", link = "Derna Sea Port", label_size = "0" },
		{ lat = "32.830", long = "12.952", mark = "Anchor pictogram green.svg", marksize = "11", label = "[[Sidi Bilal Port]]", link = "Sidi Bilal Port", label_size = "0" },
		{ lat = "32.111", long = "20.057", mark = "Anchor pictogram red.svg", marksize = "11", label = "[[Benghazi Naval Base]]", link = "Benghazi Naval Base", label_size = "0" },
		--Missing coordinates of Misrata, Tobruk, Derna and Sirte naval bases

		--Sieges & presence
		{ lat = '25.953', long = '11.306', mark = '4x4dot-green.svg', marksize = '16', label = '[[GNA presence near Al Sharara oil field]]', label_size = '0' },
		{ lat = '32.268', long = '11.901', mark = '4x4dot-green.svg', marksize = '16', label = '[[GNA presence in Nuqat al Qams District]]', label_size = '0' },
		{ lat = '31.071', long = '10.576', mark = '4x4dot-green.svg', marksize = '16', label = '[[GNA presence in Nalut District]]', label_size = '0' },
		{ lat = '26.829', long = '14.757', mark = '4x4dot-black.svg', marksize = '16', label = '[[ISIL presence in Sabha District]]', label_size = '0' },
		{ lat = '30.983', long = '14.335', mark = '4x4dot-green.svg', marksize = '16', label = '[[GNA presence to south Bani Walid]]', label_size = '0' },
		{ lat = "30.236", long = "16.9", mark = "4x4dot-red.svg", marksize = "16", label = "[[Tobruk Government presence in Sirte District]]", label_size = "0" },
		{ lat = "32.309", long = "14.058", mark = "4x4dot-green.svg", marksize = "16", label = "[[GNA forces presence in mountains of Murqub District]]", label_size = "0" },
		{ lat = "32.089", long = "14.058", mark = "4x4dot-green.svg", marksize = "16", label = "[[GNA forces presence in mountains of Bani Walid District]]", label_size = "0" },
		{ lat = "27.233", long = "12.484", mark = "4x4dot-green.svg", marksize = "16", label = "[[Tuareg forces presence]]", label_size = "0" },
		{ lat = "26.805", long = "12.781", mark = "4x4dot-green.svg", marksize = "16", label = "[[Tripoli Government presence]]", label_size = "0" },
		{ lat = "26.175", long = "10.415", mark = "4x4dot-green.svg", marksize = "16", label = "[[Tripoli Government presence]]", label_size = "0" },
		{ lat = "28.167", long = "10.2", mark = "4x4dot-green.svg", marksize = "16", label = "[[Tripoli Government presence]]", label_size = "0" },
		{ lat = "30.483", long = "14.816", mark = "4x4dot-green.svg", marksize = "16", label = "[[GNA presence to south Gheddahia]]", label_size = "0" },
		{ lat = "28.295", long = "13.790", mark = "4x4dot-green.svg", marksize = "16", label = "[[GNA presence in Wadi al Shatii]]", label_size = "0" },
		{ lat = "21.915", long = "24.985", mark = "4x4dot-black.svg", marksize = "13", label = "[[ISIL presence  in Jabal al ‘Uwaynat]]", label_size = "0" },
		},
		
	containerArgs = {
		'Libya',
		float = 'left',
		width = '2300',
		caption = [=['''Hold cursor over location to display name; click to go to location row in the "table of cities and towns" (if available).'''<br/>

*[[File:Location dot red.svg|11px]] Under the control of the [[House of Representatives (Libya)|Tobruk-based Government]], [[Libyan National Army]], and [[Zintan Brigades|Allies]]
*[[File:Dot green ff4.svg|11px]] Under the control of the [[Government of National Accord]] and affilated militias ([[Libya Shield Force]], [[Petroleum Facilities Guard]] [PFG])
*[[File:Location dot blue.svg|11px]] Under the control of local tribal forces

Contested
*[[File:80x80-red-lime-anim.gif|11px]] Tobruk Government–Government of National Accord
*[[File:80x80-red-black-anim.gif|11px]] Tobruk Government–Islamic State of Iraq and the Levant
*[[File:80x80-red-yellow-anim.gif|11px]] Tobruk Government–Gaddafi Loyalists
*[[File:80x80-red-blue-anim.gif|11px]] Tobruk Government–Local Tribal Forces
*[[File:80x80-lime-black-anim.gif|11px]] Government of National Accord–Islamic State of Iraq and the Levant
*[[File:80x80-lime-yellow-anim.gif|11px]] Government of National Accord–Gaddafi Loyalists
*[[File:80x80-lime-blue-anim.gif|11px]] Government of National Accord–Local Triabal Forces
*[[File:80x80-yellow-black-anim.gif|11px]] Islamic State of Iraq and the Levant–Gaddafi Loyalists
*[[File:80x80-blue-black-anim.gif|11px]] Islamic State of Iraq and the Levant–Local Tribal Forces
*[[File:80x80-yellow-blue-anim.gif|11px]] Gaddafi Loyalists–Local Tribal Forces


Mixed Control (Stable situation)<br>
[[File:map-ctl2-red+lime.svg|11px]] [[File:map-ctl2-red+black.svg|11px]] [[File:map-ctl2-red+yellow.svg|11px]] [[File:map-ctl2-red+blue.svg|11px]] [[File:map-ctl2-lime+black.svg|11px]] [[File:map-ctl2-lime+yellow.svg|11px]] [[File:map-ctl2-lime+blue.svg|11px]] [[File:map-ctl2-yellow+black.svg|11px]] [[File:map-ctl2-black+blue.svg|11px]] [[File:map-ctl2-yellow+blue.svg|11px]]

Besieged to one side<br>
[[File:map-arcNN-red.svg|11px]] [[File:map-arcNN-lime.svg|11px]] [[File:map-arcNN-black.svg|12px]] [[File:map-arcNN-yellow.svg|11px]] [[File:map-arcNN-blue.svg|11px]] [[File:map-arcNE-red.svg|11px]] [[File:map-arcNE-lime.svg|11px]] [[File:map-arcNE-black.svg|11px]] [[File:map-arcNE-yellow.svg|11px]] [[File:map-arcNE-blue.svg|11px]] [[File:map-arcEE-red.svg|11px]] [[File:map-arcEE-lime.svg|11px]] [[File:map-arcEE-black.svg|11px]] [[File:map-arcEE-yellow.svg|11px]] [[File:map-arcEE-blue.svg|11px]] [[File:map-arcSE-red.svg|11px]] [[File:map-arcSE-lime.svg|11px]] [[File:map-arcSE-black.svg|11px]] [[File:map-arcSE-yellow.svg|11px]] [[File:map-arcSE-blue.svg|11px]] [[File:map-arcSS-red.svg|11px]] [[File:map-arcSS-lime.svg|11px]] [[File:map-arcSS-black.svg|11px]] [[File:map-arcSS-yellow.svg|11px]] [[File:map-arcSS-blue.svg|11px]] [[File:map-arcSW-red.svg|11px]] [[File:map-arcSW-lime.svg|11px]] [[File:map-arcSW-black.svg|11px]] [[File:map-arcSW-yellow.svg|11px]] [[File:map-arcSW-blue.svg|11px]] [[File:map-arcWW-red.svg|11px]] [[File:map-arcWW-lime.svg|11px]] [[File:map-arcWW-black.svg|11px]] [[File:map-arcWW-yellow.svg|11px]] [[File:map-arcWW-blue.svg|11px]] [[File:map-arcNW-red.svg|11px]] [[File:map-arcNW-lime.svg|11px]] [[File:map-arcNW-black.svg|11px]] [[File:map-arcNW-yellow.svg|11px]] [[File:map-arcNW-blue.svg|11px]]

Besieged<br>
[[File:map-circle-red.svg|11px]] [[File:map-circle-lime.svg|11px]] [[File:map-circle-black.svg|11px]] [[File:map-circle-yellow.svg|11px]] [[File:map-circle-blue.svg|11px]]

Other
*[[File:Abm-red-icon.png|15px]] Military base
*[[File:Fighter-jet-red-icon.svg|13px]] Airport/Airbase (jet) 
*[[File:Helicopter-red-icon.svg|13px]] Airport/Airbase (helicopter)
*[[File:Abm-lime-icon.png|15px]] Military base
*[[File:Fighter-jet-lime-icon.svg|13px]] Airport/Airbase (jet) 
*[[File:Helicopter-lime-icon.svg|13px]] Airport/Airbase (helicopter) 
*[[File:Anchor_pictogram.svg|12px]] Major port or naval base
*[[File:Mountain pass 12x12 n.svg|20px]] Border Post
*[[File:Arch dam 12x12 w.svg|16px]] Dam
*[[File:Gota07.svg|10px]] Oil fields
*[[File:Icon NuclearPowerPlant-black.svg|12px]] Industrial complex
*[[File:Map-peak-red.svg|13px]] [[File:Map-peak-lime.svg|13px]] [[File:Map-peak-black.svg|13px]] [[File:Map-peak-yellow.svg|13px]] [[File:Map-peak-blue.svg|13px]] Strategic peak/hill 

Rural presence
*[[File:4x4dot-red.svg|11px]] Presence of the [[House of Representatives (Libya)|Tobruk-based Government]], [[Libyan National Army]], and [[Zintan Brigades|Allies]]
*[[File:4x4dot-lime.svg|11px]] Presence of the [[Government of National Accord]] and affilated militias ([[Libya Shield Force]], [[Petroleum Facilities Guard]] [PFG])
*[[File:4x4dot-black.svg|11px]] Presence of the [[Islamic State of Iraq and the Levant]]
*[[File:4x4dot-yellow.svg|11px]] Presence of [[Gaddafi loyalism|Gaddafi loyalists]]
*[[File:4x4dot-blue.svg|11px]] Presence of local tribal forces

<br>'''2 nested circles: inner controls, outer sieges // 3 nested circles: mixed control with stable situation  // Small icons within large circle: situation in individual neighborhoods/districts''']=]
	}
}