return {
	marks = {
		-- Coordinates are from openstreetmap, NOT GEOHACK!!!! 
		
	
		{ lat = "41.107", long = "28.976", mark = "Location dot green.svg", marksize = "50", label = "[[Istanbul]]", link = "Istanbul", label_size = "150", position = "top" },
		{ lat = "39.922", long = "32.854", mark = "Location dot green.svg", marksize = "46", label = "[[Ankara]]", link = "Ankara", label_size = "100", position = "left" },
	    { lat = "37.003", long = "35.326", mark = "Location dot green.svg", marksize = "22", label = "[[Adana]]", link = "Adana", label_size = "100", position = "bottom" },
		{ lat = "38.747", long = "41.504", mark = "Location dot green.svg", marksize = "14", label = "[[Muş]]", link = "Muş", label_size = "100", position = "top" },
		{ lat = "37.764", long = "38.276", mark = "Location dot green.svg", marksize = "20", label = "[[Adıyaman]]", link = "Adıyaman", label_size = "80", position = "bottom" },
		{ lat = "38.758", long = "30.535", mark = "Location dot green.svg", marksize = "18", label = "[[Afyonkarahisar]]", link = "Afyonkarahisar", label_size = "100", position = "bottom" },
		{ lat = "39.720", long = "43.050", mark = "Location dot green.svg", marksize = "18", label = "[[Ağrı]]", link = "Ağrı", label_size = "100", position = "top" },
	    { lat = "39.633", long = "27.883", mark = "Location dot green.svg", marksize = "20", label = "[[Balıkesir]]", link = "Balıkesir", label_size = "100", position = "bottom" },
	    { lat = "40.156", long = "26.414", mark = "Location dot green.svg", marksize = "16", label = "[[Çanakkale]]", link = "Çanakkale", label_size = "100", position = "bottom" },	
		{ lat = "40.656", long = "29.275", mark = "Location dot green.svg", marksize = "16", label = "[[Yalova]]", link = "Yalova", label_size = "100", position = "left" },	
		{ lat = "39.417", long = "29.983", mark = "Location dot green.svg", marksize = "20", label = "[[Kütahya]]", link = "Kütahya", label_size = "100", position = "bottom" },
	    { lat = "37.717", long = "30.283", mark = "Location dot green.svg", marksize = "10", label = "[[Burdur]]", link = "Burdur", label_size = "100", position = "bottom" },
	    { lat = "37.765", long = "30.557", mark = "Location dot green.svg", marksize = "14", label = "[[Isparta]]", link = "Isparta", label_size = "100", position = "right" },
	    { lat = "37.182", long = "33.218", mark = "Location dot green.svg", marksize = "16", label = "[[Karaman]]", link = "Karaman", label_size = "100", position = "top" },	
		{ lat = "40.143", long = "29.979", mark = "Location dot green.svg", marksize = "10", label = "[[Bilecik]]", link = "Bilecik", label_size = "100", position = "bottom" },
		{ lat = "40.7347", long = "31.6075", mark = "Location dot green.svg", marksize = "16", label = "[[Bolu]]", link = "Bolu", label_size = "100", position = "bottom" },
		{ lat = "40.842", long = "31.158", mark = "Location dot green.svg", marksize = "16", label = "[[Düzce]]", link = "Düzce", label_size = "100", position = "bottom" },
		{ lat = "39.921", long = "44.044", mark = "Location dot green.svg", marksize = "16", label = "[[Iğdır]]", link = "Iğdır", label_size = "100", position = "bottom" },
		{ lat = "37.583", long = "36.933", mark = "Location dot green.svg", marksize = "22", label = "[[Kahramanmaraş]]", link = "Kahramanmaraş", label_size = "100", position = "top" },
		{ lat = "37.075", long = "36.250", mark = "Location dot green.svg", marksize = "18", label = "[[Osmaniye]]", link = "Osmaniye", label_size = "100", position = "top" },
	    { lat = "37.967", long = "34.679", mark = "Location dot green.svg", marksize = "16", label = "[[Niğde]]", link = "Niğde", label_size = "100", position = "bottom" },
		{ lat = "40.650", long = "35.834", mark = "Location dot green.svg", marksize = "12", label = "[[Amasya]]", link = "Amasya", label_size = "80", position = "bottom" }, 
		{ lat = "40.7833", long = "30.400", mark = "Location dot green.svg", marksize = "18", label = "[[Adapazarı]]", link = "Adapazarı", label_size = "100", position = "bottom" },
		{ lat = "40.7667", long = "29.9167", mark = "Location dot green.svg", marksize = "22", label = "[[İzmit]]", link = "İzmit", label_size = "100", position = "top" },
		{ lat = "41.1833", long = "41.8181", mark = "Location dot green.svg", marksize = "16", label = "[[Artvin]]", link = "Artvin", label_size = "100", position = "bottom" },
		{ lat = "41.7347", long = "27.2253", mark = "Location dot green.svg", marksize = "16", label = "[[Kırklareli]]", link = "Kırklareli", label_size = "100", position = "right" },
		{ lat = "41.677", long = "26.556", mark = "Location dot green.svg", marksize = "12", label = "[[Edirne]]", link = "Edirne", label_size = "100", position = "right" },
		{ lat = "40.978", long = "27.515", mark = "Location dot green.svg", marksize = "16", label = "[[Tekirdağ]]", link = "Tekirdağ", label_size = "100", position = "bottom" },
		{ lat = "37.217", long = "28.367", mark = "Location dot green.svg", marksize = "10", label = "[[Muğla]]", link = "Muğla", label_size = "100", position = "bottom" },
		{ lat = "37.767", long = "29.083", mark = "Location dot green.svg", marksize = "20", label = "[[Denizli]]", link = "Denizli", label_size = "100", position = "bottom" },
		{ lat = "38.678", long = "29.404", mark = "Location dot green.svg", marksize = "16", label = "[[Uşak]]", link = "Uşak", label_size = "100", position = "bottom" },
		{ lat = "38.631", long = "27.422", mark = "Location dot green.svg", marksize = "18", label = "[[Manisa]]", link = "Manisa", label_size = "100", position = "bottom" },
        { lat = "41.456", long = "31.799", mark = "Location dot green.svg", marksize = "16", label = "[[Zonguldak]]", link = "Zonguldak", label_size = "100", position = "bottom" },
		{ lat = "41.6344", long = "32.3375", mark = "Location dot green.svg", marksize = "16", label = "[[Bartın]]", link = "Bartın", label_size = "100", position = "bottom" },
		{ lat = "42.033", long = "35.15", mark = "Location dot green.svg", marksize = "14", label = "[[Sinop, Turkey|Sinop]]", link = "Sinop, Turkey", label_size = "100", position = "bottom" },	
		{ lat = "41.376", long = "33.776", mark = "Location dot green.svg", marksize = "15", label = "[[Kastamonu]]", link = "Kastamonu", label_size = "100", position = "bottom" },	
		{ lat = "41.199", long = "32.626", mark = "Location dot green.svg", marksize = "16", label = "[[Karabük]]", link = "Karabük", label_size = "100", position = "bottom" },		
		{ lat = "40.600", long = "33.617", mark = "Location dot green.svg", marksize = "15", label = "[[Çankırı]]", link = "Çankırı", label_size = "100", position = "bottom" },	
		{ lat = "39.842", long = "33.514", mark = "Location dot green.svg", marksize = "15", label = "[[Kırıkkale]]", link = "Kırıkkale", label_size = "100", position = "bottom" },
		{ lat = "39.146", long = "34.161", mark = "Location dot green.svg", marksize = "15", label = "[[Kırşehir]]", link = "Kırşehir", label_size = "80", position = "bottom" },
		{ lat = "38.626", long = "34.714", mark = "Location dot green.svg", marksize = "13", label = "[[Nevşehir]]", link = "Nevşehir", label_size = "80", position = "bottom" },
		{ lat = "40.550", long = "34.954", mark = "Location dot green.svg", marksize = "14", label = "[[Çorum]]", link = "Çorum", label_size = "80", position = "bottom" },
		{ lat = "39.821", long = "34.808", mark = "Location dot green.svg", marksize = "12", label = "[[Yozgat]]", link = "Yozgat", label_size = "80", position = "bottom" },
		{ lat = "38.367", long = "34.033", mark = "Location dot green.svg", marksize = "18", label = "[[Aksaray]]", link = "Aksaray", label_size = "80", position = "bottom" },
		{ lat = "40.983", long = "37.883", mark = "Location dot green.svg", marksize = "17", label = "[[Ordu]]", link = "Ordu", label_size = "100", position = "bottom" },	
		{ lat = "40.314", long = "36.554", mark = "Location dot green.svg", marksize = "16", label = "[[Tokat]]", link = "Tokat", label_size = "100", position = "bottom" },	
		{ lat = "39.750", long = "37.017", mark = "Location dot green.svg", marksize = "20", label = "[[Sivas]]", link = "Sivas", label_size = "100", position = "bottom" },	
		{ lat = "40.915", long = "38.389", mark = "Location dot green.svg", marksize = "16", label = "[[Giresun]]", link = "Giresun", label_size = "100", position = "bottom" },
		{ lat = "39.746", long = "39.491", mark = "Location dot green.svg", marksize = "12", label = "[[Erzincan]]", link = "Erzincan", label_size = "100", position = "bottom" },
		{ lat = "40.260", long = "40.228", mark = "Location dot green.svg", marksize = "14", label = "[[Bayburt]]", link = "Bayburt", label_size = "100", position = "bottom" },
		{ lat = "40.460", long = "39.478", mark = "Location dot green.svg", marksize = "14", label = "[[Gümüşhane]]", link = "Gümüşhane", label_size = "100", position = "bottom" },
		{ lat = "41.000", long = "39.733", mark = "Location dot green.svg", marksize = "25", label = "[[Trabzon]]", link = "Trabzon", label_size = "100", position = "bottom" },
		{ lat = "41.025", long = "40.522", mark = "Location dot green.svg", marksize = "17", label = "[[Rize]]", link = "Rize", label_size = "100", position = "bottom" },
		{ lat = "37.8481", long = "27.8453", mark = "Location dot green.svg", marksize = "18", label = "[[Aydin]]", link = "Aydin", label_size = "100", position = "bottom" },
		{ lat = "37.067", long = "37.3975", mark = "Location dot green.svg", marksize = "25", label = "[[Gaziantep]]", link = "Gaziantep", label_size = "100", position = "top" },
		{ lat = "37.9264", long = "40.1984", mark = "Location dot green.svg", marksize = "20", label = "[[Diyarbakır]]", link = "Diyarbakır", label_size = "100", position = "top" },
		{ lat = "37.931", long = "41.938", mark = "Location dot green.svg", marksize = "12", label = "[[Siirt]]", link = "Siirt", label_size = "100", position = "bottom" },
	    { lat = "40.617", long = "43.100", mark = "Location dot green.svg", marksize = "12", label = "[[Kars]]", link = "Kars", label_size = "100", position = "bottom" },
		{ lat = "41.111", long = "42.702", mark = "Location dot green.svg", marksize = "10", label = "[[Ardahan]]", link = "Ardahan", label_size = "100", position = "bottom" },	
		{ lat = "38.350", long = "38.300", mark = "Location dot green.svg", marksize = "20", label = "[[Malatya]]", link = "Malatya", label_size = "100", position = "bottom" },
		{ lat = "38.667", long = "39.217", mark = "Location dot green.svg", marksize = "20", label = "[[Elazığ]]", link = "Elazığ", label_size = "100", position = "bottom" },
		{ lat = "38.401", long = "42.109", mark = "Location dot green.svg", marksize = "7", label = "[[Bitlis]]", link = "Bitlis", label_size = "100", position = "right" },
		{ lat = "37.160", long = "38.791", mark = "Location dot green.svg", marksize = "25", label = "[[Şanlıurfa]] <small>(ar-Ruhā)</small>", link = "Şanlıurfa", label_size = "100", position = "right" },
		{ lat = "37.519", long = "42.456", mark = "Location dot green.svg", marksize = "10", label = "[[Şırnak]]", link = "Şırnak", label_size = "100", position = "right" },
		{ lat = "37.319", long = "40.731", mark = "Location dot green.svg", marksize = "10", label = "[[Mardin]]", link = "Mardin", label_size = "80", position = "left" },	
		{ lat = "37.576", long = "43.737", mark = "Location dot green.svg", marksize = "12", label = "[[Hakkâri]] <small>(Colemêrg)</small>", link = "Hakkâri", label_size = "100", position = "top" },
        { lat = "36.205", long = "36.158", mark = "Location dot green.svg", marksize = "20", label = "[[Antakya]]", link = "Antakya", label_size = "100", position = "bottom" },
        { lat = "38.438", long = "27.040", mark = "Location dot green.svg", marksize = "35", label = "[[İzmir]]", link = "İzmir", label_size = "100", position = "left" },
        { lat = "40.183", long = "29.05", mark = "Location dot green.svg", marksize = "30", label = "[[Bursa]]", link = "Bursa", label_size = "100", position = "bottom" },
        { lat = "37.871", long = "32.485", mark = "Location dot green.svg", marksize = "26", label = "[[Konya]]", link = "Konya", label_size = "100", position = "bottom" },
        { lat = "36.908", long = "30.696", mark = "Location dot green.svg", marksize = "25", label = "[[Antalya]]", link = "Antalya", label_size = "100", position = "top" },
        { lat = "38.732", long = "35.485", mark = "Location dot green.svg", marksize = "25", label = "[[Kayseri]]", link = "Kayseri", label_size = "100", position = "bottom" },
        { lat = "36.795", long = "34.618", mark = "Location dot green.svg", marksize = "25", label = "[[Mersin]]", link = "Mersin", label_size = "100", position = "top" },
        { lat = "39.777", long = "30.521", mark = "Location dot green.svg", marksize = "25", label = "[[Eskişehir]]", link = "Eskişehir", label_size = "100", position = "bottom" },
{ lat = "39.384", long = "32.331", mark = "Location dot green.svg", marksize = "14", label = "[[Polatlı]]", link = "Polatlı", label_size = "100", position = "bottom" },
        { lat = "41.283", long = "36.333", mark = "Location dot green.svg", marksize = "25", label = "[[Samsun]]", link = "Samsun", label_size = "100", position = "bottom" },
        { lat = "38.492", long = "43.383", mark = "Location dot green.svg", marksize = "18", label = "[[Van, Turkey|Van]]", link = "Van, Turkey", label_size = "80", position = "top" },
        { lat = "37.887", long = "41.132", mark = "Location dot green.svg", marksize = "14", label = "[[Batman, Turkey|Batman]] <small>(Êlih)</small>", link = "Batman, Turkey", label_size = "80", position = "bottom" },
        { lat = "39.107", long = "39.544", mark = "Location dot green.svg", marksize = "10", label = "[[Tunceli]] <small>(Dersim)</small>", link = "Tunceli", label_size = "100", position = "top" },
        { lat = "36.718", long = "37.115", mark = "Location dot green.svg", marksize = "16", label = "[[Kilis]]", link = "Kilis", label_size = "100", position = "right" },
        { lat = "39.541", long = "43.671", mark = "Location dot green.svg", marksize = "8", label = "[[Diyadin]]", link = "Diyadin", label_size = "80", position = "top" },
		{ lat = "39.798", long = "42.675", mark = "Location dot green.svg", marksize = "8", label = "[[Eleşkirt]]", link = "Eleşkirt", label_size = "80", position = "top" },
		{ lat = "39.609", long = "42.989", mark ="Location dot green.svg", marksize = "6", label = "[[Hamur]]", link = "Hamur", label_size = "80", position = "bottom" },
		{ lat = "39.539", long = "42.772", mark = "Location dot green.svg", marksize = "6", label = "[[Tutak, Turkey|Tutak]]", link = "Tutak, Turkey", label_size = "80", position = "top" },
		{ lat = "39.633", long = "43.377", mark = "Location dot green.svg", marksize = "5", label = "[[Taşlıçay]]", link = "Taşlıçay", label_size = "80", position = "top" },
		{ lat = "39.234", long = "42.861", mark = "Location dot green.svg", marksize = "11", label = "[[Patnos]]", link = "Patnos", label_size = "80", position = "top" },
		{ lat = "38.944", long = "38.714", mark = "Location dot green.svg", marksize = "4", label = "[[Ağın]]", link = "Ağın", label_size = "80", position = "bottom" },
		{ lat = "38.564", long = "40.136", mark = "Location dot green.svg", marksize = "5", label = "[[Arıcak]]", link = "Arıcak", label_size = "80", position = "left" },
		{ lat = "38.569", long = "38.822", mark = "Location dot green.svg", marksize = "5", label = "[[Baskil]]", link = "Baskil", label_size = "80", position = "top" },
        { lat = "38.463", long = "39.863", mark = "Location dot green.svg", marksize = "7", label = "[[Alacakaya]]", link = "Alacakaya", label_size = "80", position = "left" },
		{ lat = "38.956", long = "40.038", mark = "Location dot green.svg", marksize = "9", label = "[[Karakoçan]]", link = "Karakoçan", label_size = "80", position = "bottom" },
		{ lat = "38.794", long = "38.740", mark = "Location dot green.svg", marksize = "4", label = "[[Keban, Elazığ|Keban]]", link = "Keban, Elazığ", label_size = "80", position = "bottom" },
		{ lat = "38.719", long = "39.866", mark = "Location dot green.svg", marksize = "7", label = "[[Kovancılar]]", link = "Kovancılar", label_size = "80", position = "left" },
	    { lat = "38.693", long = "39.929", mark = "Location dot green.svg", marksize = "6", label = "[[Palu, Elazığ|Palu]]", link = "Palu, Elazığ", label_size = "80", position = "right" },
	    { lat = "38.447", long = "39.308", mark = "Location dot green.svg", marksize = "5", label = "[[Sivrice, Elazığ|Sivrice]]", link = "Sivrice, Elazığ", label_size = "80", position = "bottom" },
	    { lat = "38.393", long = "39.670", mark = "Location dot green.svg", marksize = "5", label = "[[Maden]]", link = "Maden", label_size = "80", position = "bottom" },
                { lat = "38.160", long = "42.0018", mark = "Location dot green.svg", marksize = "4", label = "[[Ormanbağı]]", link = "Ormanbağı", label_size = "0", position = "top" },
		{ lat = "38.179", long = "42.229", mark = "Location dot green.svg", marksize = "4", label = "[[Cevizlik]]", link = "Cevizlik", label_size = "0", position = "top" },
		{ lat = "37.976", long = "42.648", mark = "Location dot green.svg", marksize = "5", label = "[[Beğendik]]", link = "Beğendik", label_size = "0", position = "top" },
		{ lat = "37.763", long = "42.789", mark = "Location dot green.svg", marksize = "5", label = "[[Doğanköy]]", link = "Doğanköy", label_size = "0", position = "top" },
		{ lat = "37.695", long = "42.108", mark = "Location dot green.svg", marksize = "4", label = "[[Dikboğaz]]", link = "Dikboğaz", label_size = "0", position = "top" },
		{ lat = "37.710", long = "41.918", mark = "Location dot green.svg", marksize = "4", label = "[[Bağgöze]]", link = "Bağgöze", label_size = "0", position = "top" },
    	{ lat = "37.619", long = "42.556", mark = "Location dot green.svg", marksize = "4", label = "[[Dicle (Şırnak)]]", link = "Dicle (Şırnak)", label_size = "0", position = "top" },
		{ lat = "37.330", long = "42.186", mark = "Location dot green.svg", marksize = "12", label = "[[Cizre]]", link = "Cizre", label_size = "80", position = "top" },
		{ lat = "39.148", long = "42.544", mark = "Location dot green.svg", marksize = "8", label = "[[Malazgirt]]", link = "Malazgirt", label_size = "80", position = "top" },
		{ lat = "38.739", long = "41.783", mark = "Location dot green.svg", marksize = "5", label = "[[Korkut]]", link = "Korkut", label_size = "80", position = "top" },
		{ lat = "38.682", long = "41.689", mark = "Location dot green.svg", marksize = "7", label = "[[Hasköy, Muş|Hasköy]]", link = "Hasköy, Muş", label_size = "80", position = "right" },
		{ lat = "39.171", long = "41.454", mark = "Location dot green.svg", marksize = "6", label = "[[Varto]] <small>(Gımgım)</small>", link = "Varto", label_size = "80", position = "top" },
		{ lat = "38.143", long = "41.008", mark = "Location dot green.svg", marksize = "7", label = "[[Silvan, Diyarbakır|Silvan]] <small>(Farqîn)</small>", link = "Silvan, Diyarbakır", label_size = "80", position = "bottom" },
        { lat = "38.459", long = "40.648", mark = "Location dot green.svg", marksize = "8", label = "[[Lice, Turkey|Lice]]", link = "Lice, Turkey", label_size = "80", position = "top" },
      	{ lat = "38.136", long = "39.4525", mark = "Location dot green.svg", marksize = "6", label = "[[Çermik]]", link = "Çermik", label_size = "80", position = "bottom" },
		{ lat = "37.724", long = "40.415", mark = "Location dot green.svg", marksize = "7", label = "[[Çınar, Diyarbakır|Çınar]]", link = "Çınar, Diyarbakır", label_size = "80", position = "top" },
	    { lat = "38.213", long = "39.288", mark = "Location dot green.svg", marksize = "5", label = "[[Çüngüş]]", link = "Çüngüş", label_size = "80", position = "bottom" },
		{ lat = "38.375", long = "40.074", mark = "Location dot green.svg", marksize = "5", label = "[[Dicle]]", link = "Dicle", label_size = "80", position = "bottom" },
		{ lat = "38.258", long = "40.083", mark = "Location dot green.svg", marksize = "6", label = "[[Eğil]]", link = "Eğil", label_size = "80", position = "bottom" },
		{ lat = "38.267", long = "39.762", mark = "Location dot green.svg", marksize = "11", label = "[[Ergani]]", link = "Ergani", label_size = "80", position = "bottom" },
		{ lat = "38.413", long = "40.394", mark = "Location dot green.svg", marksize = "6", label = "[[Hani, Turkey|Hani]]", link = "Hani, Turkey", label_size = "80", position = "bottom" },
		{ lat = "38.2541", long = "40.7815", mark = "Location dot green.svg", marksize = "6", label = "[[Hazro, Diyarbakır|Hazro]]", link = "Hazro, Diyarbakır", label_size = "80", position = "top" },
		{ lat = "38.289", long = "40.502", mark = "Location dot green.svg", marksize = "8", label = "[[Kocaköy]]", link = "Kocaköy", label_size = "80", position = "bottom" },
		{ lat = "38.499", long = "41.0105", mark = "Location dot green.svg", marksize = "7", label = "[[Kulp, Turkey|Kulp]]", link = "Kulp, Turkey", label_size = "80", position = "top" },
	    { lat = "37.851", long = "40.667", mark = "Location dot green.svg", marksize = "8", label = "[[Bismil]]", link = "Bismil", label_size = "80", position = "top" },
		{ lat = "40.142", long = "43.122", mark = "Location dot green.svg", marksize = "10", label = "[[Kağızman]]", link = "Kağızman", label_size = "80", position = "top" },
		{ lat = "40.741", long = "43.625", mark = "Location dot green.svg", marksize = "6", label = "[[Akyaka, Kars|Akyaka]]", link = "Akyaka, Kars", label_size = "80", position = "left" },
		{ lat = "38.805", long = "42.734", mark = "Location dot green.svg", marksize = "5", label = "[[Adilcevaz]]", link = "Adilcevaz", label_size = "80", position = "top" },
		{ lat = "38.754", long = "42.486", mark = "Location dot green.svg", marksize = "5", label = "[[Ahlat]]", link = "Ahlat", label_size = "80", position = "top" },
		{ lat = "38.578", long = "42.018", mark = "Location dot green.svg", marksize = "5", label = "[[Güroymak]]", link = "Güroymak", label_size = "80", position = "bottom" },
		{ lat = "38.224", long = "42.422", mark = "Location dot green.svg", marksize = "5", label = "[[Hizan]]", link = "Hizan", label_size = "80", position = "top" }, 
		{ lat = "38.118", long = "42.482", mark = "Location dot green.svg", marksize = "3", label = "[[Yolbilen (Xulebir)]]", label_size = "0" }, 
		{ lat = "38.1278", long = "42.455", mark = "Location dot green.svg", marksize = "3", label = "[[Yaylacık (Akunüs)]]", label_size = "0" }, 
		{ lat = "38.1345", long = "42.5034", mark = "Location dot green.svg", marksize = "3", label = "[[Çalışkanlar (Kekulan)]]", label_size = "0" }, 
		{ lat = "38.0916", long = "42.5327", mark = "Location dot green.svg", marksize = "3", label = "[[Sarıtaş (Huzera)]]", label_size = "0" }, 
		{ lat = "38.135", long = "42.7772", mark = "Location dot green.svg", marksize = "3", label = "[[Bilgili (Haret)]]", label_size = "0" }, 
		{ lat = "38.409", long = "41.924", mark = "Location dot green.svg", marksize = "4", label = "[[Mutki]]", link = "Mutki", label_size = "80", position = "bottom" },
		{ lat = "38.502", long = "42.281", mark = "Location dot green.svg", marksize = "5", label = "[[Tatvan]]", link = "Tatvan", label_size = "80", position = "top" },
		{ lat = "38.892", long = "40.499", mark = "Location dot green.svg", marksize = "12", label = "[[Bingöl]] <small>(Çewlîg)</small>", link = "Bingöl", label_size = "80", position = "top" },
		{ lat = "39.296", long = "41.011", mark = "Location dot green.svg", marksize = "5", label = "[[Karlıova]]", link = "Karlıova", label_size = "80", position = "top" },
        { lat = "39.229", long = "40.483", mark = "Location dot green.svg", marksize = "4", label = "[[Adaklı]]", link = "Adaklı", label_size = "80", position = "top" },
		{ lat = "38.750", long = "40.557", mark = "Location dot green.svg", marksize = "5", label = "[[Genç]] <small>(Darahênî)</small>", link = "Genç", label_size = "80", position = "right" },
		{ lat = "39.310", long = "40.350", mark = "Location dot green.svg", marksize = "4", label = "[[Kiğı]]", link = "Kiğı", label_size = "80", position = "top" },
		{ lat = "38.968", long = "41.051", mark = "Location dot green.svg", marksize = "6", label = "[[Solhan]]", link = "Solhan", label_size = "80", position = "top" },
		{ lat = "39.226", long = "40.069", mark = "Location dot green.svg", marksize = "4", label = "[[Yayladere]] <small>(Xorxol)</small>", link = "Yayladere", label_size = "80", position = "top" },
		{ lat = "39.435", long = "40.545", mark = "Location dot green.svg", marksize = "4", label = "[[Yedisu]]", link = "Yedisu", label_size = "80", position = "top" },
		{ lat = "37.192", long = "40.583", mark = "Location dot green.svg", marksize = "11", label = "[[Kızıltepe]] <small>(Qoser)</small>", link = "Kızıltepe", label_size = "80", position = "left" },
		{ lat = "37.386", long = "40.568", mark = "Location dot green.svg", marksize = "6", label = "[[Cevizlik]]", link = "Cevizlik", label_size = "0", position = "top" },
	    { lat = "39.062", long = "38.912", mark = "Location dot green.svg", marksize = "6", label = "[[Çemişgezek]] <small>(Melkişî)</small>", link = "Çemişgezek", label_size = "80", position = "top" },
        { lat = "39.109", long = "39.220", mark = "Location dot green.svg", marksize = "6", label = "[[Hozat]]", link = "Hozat", label_size = "80", position = "bottom" },
        { lat = "39.022", long = "39.608", mark = "Location dot green.svg", marksize = "5", label = "[[Mazgirt]]", link = "Mazgirt", label_size = "80", position = "bottom" },
        { lat = "39.181", long = "39.829", mark = "Location dot green.svg", marksize = "5", label = "[[Nazımiye]] <small>(Qisle)</small>", link = "Nazımiye", label_size = "80", position = "bottom" },
      	{ lat = "39.359", long = "39.216", mark = "Location dot green.svg", marksize = "5", label = "[[Ovacık, Dersim|Ovacık]] <small>(Pûlûr)</small>", link = "Ovacık, Dersim", label_size = "80", position = "left" },
      	{ lat = "38.867", long = "39.325", mark = "Location dot green.svg", marksize = "8", label = "[[Pertek]]", link = "Pertek", label_size = "80", position = "top" },
      	{ lat = "39.487", long = "39.899", mark = "Location dot green.svg", marksize = "6", label = "[[Pülümür]]", link = "Pülümür", label_size = "80", position = "right" },
      	{ lat = "38.852", long = "39.678", mark = "Location dot green.svg", marksize = "5", label = "[[Akpazar]]", link = "Akpazar", label_size = "0", position = "bottom" },
	    { lat = "39.050", long = "39.500", mark = "Location dot green.svg", marksize = "3", label = "[[Aktuluk]]", link = "Aktuluk", label_size = "0", position = "bottom" },
	    { lat = "39.300", long = "39.132", mark = "Location dot green.svg", marksize = "3", label = "[[Arslandoğmuş, Ovacık|Arslandoğmuş]]", link = "Arslandoğmuş, Ovacık", label_size = "0", position = "bottom" },
	    { lat = "38.967", long = "39.533", mark = "Location dot green.svg", marksize = "4", label = "[[Burmageçit]]", link = "Burmageçit", label_size = "0", position = "bottom" },
	    { lat = "38.967", long = "39.800", mark = "Location dot green.svg", marksize = "4", label = "[[Darıkent]]", link = "Darıkent", label_size = "0", position = "bottom" },
	    { lat = "39.350", long = "39.117", mark = "Location dot green.svg", marksize = "4", label = "[[Koyungölü]]", link = "Koyungölü", label_size = "0", position = "bottom" },
	    { lat = "38.967", long = "38.983", mark = "Location dot green.svg", marksize = "4", label = "[[Payamdüzü]]", link = "Payamdüzü", label_size = "0", position = "bottom" },
	    { lat = "39.000", long = "38.950", mark = "Location dot green.svg", marksize = "4", label = "[[Sarıbalta]]", link = "Sarıbalta", label_size = "0", position = "bottom" },
	    { lat = "41.917", long = "27.367", mark = "Location dot green.svg", marksize = "3", label = "[[Dereköy, Kırklareli|Dereköy]]", link = "Dereköy, Kırklareli", label_size = "0", position = "left" },
		{ lat = "36.976", long = "38.425", mark = "Location dot green.svg", marksize = "8", label = "[[Suruç]] <small>(Pirsûs)</small>", link = "Suruç", label_size = "80", position = "top" },
		{ lat = "36.713", long = "38.948", mark = "Location dot green.svg", marksize = "8", label = "[[Akçakale]]", link = "Akçakale", label_size = "80", position = "top" },
		{ lat = "37.307", long = "44.572", mark = "Location dot green.svg", marksize = "7", label = "[[Şemdinli]] <small>(Şemzînan)</small>", link = "Şemdinli", label_size = "80", position = "bottom" },
	    { lat = "37.249", long = "42.469", mark = "Location dot green.svg", marksize = "10", label = "[[Silopi]]", link = "Silopi", label_size = "80", position = "top" },
	    { lat = "37.199", long = "42.519", mark = "Location dot green.svg", marksize = "8", label = "[[Cumhuriyet]]", link = "Cumhuriyet", label_size = "80", position = "left" },
        { lat = "39.095", long = "42.267", mark = "Location dot green.svg", marksize = "5", label = "[[Bulanık]] <small>(Kop)</small>", link = "Bulanık", label_size = "80", position = "bottom" },
        { lat = "37.567", long = "44.284", mark = "Location dot green.svg", marksize = "8", label = "[[Yüksekova]] <small>(Gever)</small>", link = "Yüksekova", label_size = "80", position = "bottom" },
        { lat = "37.374", long = "44.086", mark = "Location dot green.svg", marksize = "4", label = "[[Dağlıca]]", link = "Dağlıca", label_size = "0", position = "top" },
        { lat = "39.547", long = "44.084", mark = "Location dot green.svg", marksize = "10", label = "[[Doğubeyazıt]]", link = "Doğubeyazıt", label_size = "80", position = "top" },
        { lat = "37.948", long = "40.171", mark = "Location dot green.svg", marksize = "11", label = "Kayapınar", link = "Kayapınar, Diyarbakır", label_size = "0", position = "top" },
        { lat = "38.426", long = "43.257", mark = "Location dot green.svg", marksize = "5", label = "[[Edremit, Van|Edremit]]", link = "Edremit, Van", label_size = "80", position = "bottom" },
        { lat = "38.125", long = "42.807", mark = "Location dot green.svg", marksize = "5", label = "[[Bahçesaray (District), Van|Bahçesaray]]", link = "Bahçesaray (District), Van", label_size = "80", position = "bottom" },
        { lat = "38.044", long = "44.018", mark = "Location dot green.svg", marksize = "5", label = "[[Başkale]] <small>(Elbak)</small>", link = "Başkale", label_size = "80", position = "bottom" },
        { lat = "39.139", long = "43.907", mark = "Location dot green.svg", marksize = "5", label = "[[Çaldıran (District), Van|Çaldıran]]", link = "Çaldıran (District), Van", label_size = "80", position = "bottom" },
        { lat = "38.008", long = "43.062", mark = "Location dot green.svg", marksize = "5", label = "[[Çatak]]", link = "Çatak", label_size = "80", position = "bottom" },
        { lat = "39.028", long = "43.359", mark = "Location dot green.svg", marksize = "5", label = "[[Erciş]]", link = "Erciş", label_size = "80", position = "bottom" },
        { lat = "38.295", long = "43.108", mark = "Location dot green.svg", marksize = "6", label = "[[Gevaş]]", link = "Gevaş", label_size = "80", position = "bottom" },
        { lat = "38.649", long = "44.171", mark = "Location dot green.svg", marksize = "5", label = "[[Saray (District), Van|Saray]]", link = "Saray (District), Van", label_size = "80", position = "top" },
        { lat = "38.657", long = "43.990", mark = "Location dot green.svg", marksize = "5", label = "[[Özalp, Van|Özalp]]", link = "Özalp, Van", label_size = "80", position = "bottom" },
        { lat = "38.323", long = "43.408", mark = "Location dot green.svg", marksize = "3", label = "[[Gürpınar (District), Van|Gürpınar]]", link = "Gürpınar (District), Van", label_size = "80", position = "bottom" },
        { lat = "38.987", long = "43.759", mark = "Location dot green.svg", marksize = "6", label = "[[Muradiye (District), Van|Muradiye]]", link = "Muradiye (District), Van", label_size = "80", position = "bottom" },
        { lat = "38.466", long = "43.404", mark = "Location dot green.svg", marksize = "7", label = "Hacıbekir Mahallesi <small>(Xaçort)</small>", link = "Hacıbekir", label_size = "0", position = "top" },
        { lat = "39.973", long = "44.173", mark = "Location dot green.svg", marksize = "5", label = "[[Karakoyunlu]]", link = "Karakoyunlu", label_size = "80", position = "top" },
        { lat = "38.380", long = "41.395", mark = "Location dot green.svg", marksize = "5", label = "[[Sason]] <small>(Qabilcewz)</small>", link = "Sason", label_size = "80", position = "bottom" },
        { lat = "37.920", long = "41.290", mark = "Location dot green.svg", marksize = "7", label = "[[Beşiri]]", link = "Beşiri", label_size = "80", position = "bottom" },
        { lat = "37.566", long = "41.384", mark = "Location dot green.svg", marksize = "5", label = "[[Gercüş]]", link = "Gercüş", label_size = "80", position = "right" },
        { lat = "37.714", long = "41.413", mark = "Location dot green.svg", marksize = "4", label = "[[Hasankeyf]]", link = "Hasankeyf", label_size = "80", position = "bottom" },
        { lat = "38.170", long = "41.497", mark = "Location dot green.svg", marksize = "8", label = "[[Kozluk]]", link = "Kozluk", label_size = "80", position = "bottom" },
        { lat = "38.497", long = "44.320", mark = "Location dot green.svg", marksize = "4" },
        { lat = "39.909", long = "41.277", mark = "Location dot green.svg", marksize = "20", label = "[[Erzurum]]", link = "Erzurum", label_size = "100", position = "bottom" },
        { lat = "39.703", long = "42.144", mark = "Location dot green.svg", marksize = "5", label = "[[Karayazı]]", link = "Karayazı", label_size = "80", position = "top" },
        { lat = "39.359", long = "41.699", mark = "Location dot green.svg", marksize = "6", label = "[[Hınıs]]", link = "Hınıs", label_size = "80", position = "top" },
        { lat = "39.646", long = "41.509", mark = "Location dot green.svg", marksize = "5", label = "[[Tekman]] <small>(Tatos)</small>", link = "Tekman", label_size = "80", position = "right" },
        { lat = "39.350", long = "42.112", mark = "Location dot green.svg", marksize = "5", label = "[[Karaçoban]]", link = "Karaçoban", label_size = "80", position = "top" },
        { lat = "37.417", long = "42.900", mark = "Location dot green.svg", marksize = "10", label = "[[Uludere]]", link = "Uludere", label_size = "75", position = "top" },
        { lat = "37.3907", long = "42.987", mark = "Location dot green.svg", marksize = "6", label = "[[Gülyazı, Kızılören|Gülyazı]]", link = "Gülyazı, Kızılören", label_size = "80", position = "right" },
        { lat = "37.368", long = "42.958", mark = "Location dot green.svg", marksize = "5", label = "[[Ortasu]]", link = "Ortasu", label_size = "0", position = "top" },
        { lat = "37.471", long = "41.915", mark = "Location dot green.svg", marksize = "6", label = "[[Güçlükonak]]", link = "Güçlükonak", label_size = "80", position = "right" },
        { lat = "37.571", long = "43.167", mark = "Location dot green.svg", marksize = "5", label = "[[Beytüşşebap]]", link = "Beytüşşebap", label_size = "80", position = "top" },
        { lat = "37.3298", long = "43.3838", mark = "Location dot green.svg", marksize = "5", label = "[[Çığlı (Aşîtha)]]", label_size = "0" },
        { lat = "37.342", long = "41.892", mark = "Location dot green.svg", marksize = "10", label = "[[İdil]] <small>(Hezex)</small>", link = "İdil", label_size = "80", position = "bottom" },
        { lat = "37.417", long = "41.370", mark = "Location dot green.svg", marksize = "10", label = "[[Midyat]]", link = "Midyat", label_size = "80", position = "bottom" },
        { lat = "37.350", long = "40.817", mark = "Location dot green.svg", marksize = "4", label = "[[Kabala, Mardin|Kabala]]", link = "Kabala, Mardin", label_size = "0", position = "bottom" },
        { lat = "37.495", long = "41.626", mark = "Location dot green.svg", marksize = "4", label = "[[Beth Kustan, Mardin|Beth Kustan]]", link = "Beth Kustan, Mardin", label_size = "0", position = "bottom" },
        { lat = "37.467", long = "40.583", mark = "Location dot green.svg", marksize = "4", label = "[[Bilge, Mardin|Bilge]] (Zanqirt)", link = "Bilge, Mardin", label_size = "0", position = "bottom" },
        { lat = "37.545", long = "41.720", mark = "Location dot green.svg", marksize = "4", label = "[[Dargeçit]]", link = "Dargeçit", label_size = "80", position = "bottom" },
        { lat = "37.366", long = "40.270", mark = "Location dot green.svg", marksize = "5", label = "[[Derik, Turkey|Derik]]", link = "Derik, Turkey", label_size = "80", position = "bottom" },
        { lat = "37.083", long = "40.417", mark = "Location dot green.svg", marksize = "4", label = "[[Dikmen, Mardin|Dikmen]]", link = "Dikmen, Mardin", label_size = "0", position = "bottom" },
        { lat = "37.417", long = "41.267", mark = "Location dot green.svg", marksize = "5", label = "[[Gelinkaya]]", link = "Gelinkaya", label_size = "0", position = "bottom" },
        { lat = "37.200", long = "40.700", mark = "Location dot green.svg", marksize = "4", label = "[[Gökçe, Mardin|Gökçe]] (Selax)", link = "Gökçe, Mardin", label_size = "0", position = "bottom" },
        { lat = "37.479", long = "40.486", mark = "Location dot green.svg", marksize = "4", label = "[[Mazıdağı]]", link = "Mazıdağı", label_size = "80", position = "left" },
        { lat = "37.341", long = "40.826", mark = "Location dot green.svg", marksize = "4", label = "[[Yeşilli]]", link = "Yeşilli", label_size = "80", position = "bottom" },
        { lat = "37.533", long = "41.650", mark = "Location dot green.svg", marksize = "4", label = "[[Sümer, Mardin|Sümer]]", link = "Sümer, Mardin", label_size = "0", position = "bottom" },
        { lat = "37.538", long = "40.889", mark = "Location dot green.svg", marksize = "5", label = "[[Savur]]", link = "Savur", label_size = "80", position = "right" },
        { lat = "37.217", long = "40.783", mark = "Location dot green.svg", marksize = "4", label = "[[Ortaköy, Mardin|Ortaköy]]", link = "Ortaköy, Mardin", label_size = "0", position = "bottom" },
        { lat = "37.403", long = "40.956", mark = "Location dot green.svg", marksize = "4", label = "[[Ömerli, Mardin|Ömerli]]", link = "Ömerli, Mardin", label_size = "80", position = "bottom" },
        { lat = "36.675", long = "37.466", mark = "Location dot green.svg", marksize = "4", label = "[[Elbeyli]]", link = "Elbeyli", label_size = "80", position = "right" },
        { lat = "37.273", long = "41.484", mark = "Location dot green.svg", marksize = "3", label = "[[Taşköy, Nusaybin|Taşköy]] (Arboy)", link = "Taşköy, Nusaybin", label_size = "0", position = "bottom" },
        { lat = "37.328", long = "41.342", mark = "Location dot green.svg", marksize = "3", label = "[[Yemişli, Midyat|Yemişli]] (Hilhil)", link = "Yemişli, Midyat", label_size = "0", position = "bottom" },
        { lat = "36.886", long = "36.918", mark = "Location dot green.svg", marksize = "4", label = "[[Musabeyli]]", link = "Musabeyli", label_size = "80", position = "top" },
        { lat = "36.883", long = "36.817", mark = "Location dot green.svg", marksize = "3", label = "[[Hasancalı]]", link = "Hasancalı", label_size = "0", position = "bottom" },
        { lat = "36.842", long = "37.134", mark = "Location dot green.svg", marksize = "5", label = "[[Polateli]]", link = "Polateli", label_size = "80", position = "up" },
        { lat = "36.700", long = "37.267", mark = "Location dot green.svg", marksize = "3", label = "[[Yavuzlu]]", link = "Yavuzlu", label_size = "0", position = "bottom" },
        { lat = "36.933", long = "36.917", mark = "Location dot green.svg", marksize = "3", label = "[[Tahtalıkaradut]]", link = "Tahtalıkaradut", label_size = "0", position = "bottom" },
        { lat = "36.833", long = "36.800", mark = "Location dot green.svg", marksize = "3", label = "[[Gülbaba, Kilis|Gülbaba]]", link = "Gülbaba, Kilis", label_size = "0", position = "bottom" },
        { lat = "36.833", long = "37.050", mark = "Location dot green.svg", marksize = "3", label = "[[Bağarası, Polateli|Bağarası]]", link = "Bağarası, Polateli", label_size = "0", position = "bottom" },
        { lat = "37.025", long = "37.977", mark = "Location dot green.svg", marksize = "10", label = "[[Birecik]]", link = "Birecik", label_size = "80", position = "top" },
        { lat = "37.363", long = "38.526", mark = "Location dot green.svg", marksize = "10", label = "[[Bozova]]", link = "Bozova", label_size = "80", position = "left" },
        { lat = "36.878", long = "39.034", mark = "Location dot green.svg", marksize = "10", label = "[[Harran]]", link = "Harran", label_size = "80", position = "top" },
        { lat = "37.249", long = "37.866", mark = "Location dot green.svg", marksize = "8", label = "[[Halfeti]]", link = "Halfeti", label_size = "80", position = "right" },
        { lat = "37.589", long = "38.956", mark = "Location dot green.svg", marksize = "3", label = "[[Hilvan]]", link = "Hilvan", label_size = "80", position = "right" },
        { lat = "37.750", long = "39.317", mark = "Location dot green.svg", marksize = "15", label = "[[Siverek]] <small>(Sêwreg)</small>", link = "Siverek", label_size = "80", position = "top" },
        { lat = "36.863", long = "38.636", mark = "Location dot green.svg", marksize = "3", label = "[[Uğurtaş, Akçakale|Uğurtaş]]", link = "Uğurtaş, Akçakale", label_size = "0", position = "right" },
        { lat = "37.231", long = "39.765", mark = "Location dot green.svg", marksize = "4", label = "[[Viranşehir]] <small>(Wêranşar)</small>", link = "Viranşehir", label_size = "80", position = "top" },
        { lat = "37.951", long = "42.013", mark = "Location dot green.svg", marksize = "3", label = "[[Tillo]]", link = "Tillo", label_size = "80", position = "right" },
        { lat = "38.164", long = "41.785", mark = "Location dot green.svg", marksize = "5", label = "[[Baykan]]", link = "Baykan", label_size = "80", position = "bottom" },
        { lat = "37.750", long = "42.180", mark = "Location dot green.svg", marksize = "6", label = "[[Eruh]] <small>(Dih)</small>", link = "Eruh", label_size = "80", position = "bottom" },
        { lat = "37.999", long = "42.709", mark = "Location dot green.svg", marksize = "3", label = "[[Gümüşören, Pervari|Gümüşören]]", link = "Gümüşören, Pervari", label_size = "0", position = "bottom" },
        { lat = "37.926", long = "41.700", mark = "Location dot green.svg", marksize = "7", label = "[[Kurtalan]]", link = "Kurtalan", label_size = "80", position = "top" },
        { lat = "37.933", long = "42.547", mark = "Location dot green.svg", marksize = "5", label = "[[Pervari]] <small>(Xisxêr)</small>", link = "Pervari", label_size = "80", position = "bottom" },
        { lat = "38.063", long = "42.028", mark = "Location dot green.svg", marksize = "5", label = "[[Şirvan]]", link = "Şirvan", label_size = "80", position = "right" },
        { lat = "36.900", long = "36.567", mark = "Location dot green.svg", marksize = "5", label = "[[Yeşilyurt, Gaziantep|Yeşilyurt]]", link = "Yeşilyurt, Gaziantep", label_size = "0", position = "bottom" },
        { lat = "36.933", long = "36.550", mark = "Location dot green.svg", marksize = "5", label = "[[Boğaziçi, Gaziantep|Boğaziçi]]", link = "Boğaziçi, Gaziantep", label_size = "0", position = "bottom" },
        { lat = "36.933", long = "36.567", mark = "Location dot green.svg", marksize = "5", label = "[[Altınüzüm]]", link = "Altınüzüm", label_size = "0", position = "bottom" },
        { lat = "37.425", long = "37.693", mark = "Location dot green.svg", marksize = "7", label = "[[Araban]]", link = "Araban", label_size = "80", position = "right" },
        { lat = "37.150", long = "37.367", mark = "Location dot green.svg", marksize = "4", label = "[[Dülük]]", link = "Dülük", label_size = "0", position = "bottom" },
        { lat = "37.383", long = "37.883", mark = "Location dot green.svg", marksize = "4", label = "[[Elif, Gaziantep|Elifköy]]", link = "Elif, Gaziantep", label_size = "0", position = "bottom" },
        { lat = "37.100", long = "36.600", mark = "Location dot green.svg", marksize = "4", label = "[[Fevzipaşa]]", link = "Fevzipaşa", label_size = "0", position = "bottom" },
        { lat = "37.025", long = "36.635", mark = "Location dot green.svg", marksize = "7", label = "[[İslahiye]]", link = "İslahiye", label_size = "80", position = "right" },
        { lat = "37.010", long = "37.797", mark = "Location dot green.svg", marksize = "7", label = "[[Nizip]]", link = "Nizip", label_size = "80", position = "bottom" },
        { lat = "37.319", long = "37.569", mark = "Location dot green.svg", marksize = "5", label = "[[Yavuzeli]]", link = "Yavuzeli", label_size = "80", position = "top" },
        { lat = "37.179", long = "36.740", mark = "Location dot green.svg", marksize = "6", label = "[[Nurdağı]]", link = "Nurdağı", label_size = "80", position = "top" },
        { lat = "36.965", long = "37.509", mark = "Location dot green.svg", marksize = "7", label = "[[Oğuzeli]]", link = "Oğuzeli", label_size = "80", position = "bottom" },
	    { lat = "37.694", long = "37.861", mark = "Location dot green.svg", marksize = "8", label = "[[Besni]]", link = "Besni", label_size = "80", position = "top" },
	    { lat = "38.035", long = "38.246", mark = "Location dot green.svg", marksize = "7", label = "[[Çelikhan]]", link = "Çelikhan", label_size = "80", position = "bottom" },
	    { lat = "38.029", long = "39.032", mark = "Location dot green.svg", marksize = "5", label = "[[Gerger]]", link = "Gerger", label_size = "80", position = "bottom" },
	    { lat = "37.784", long = "37.6444", mark = "Location dot green.svg", marksize = "8", label = "[[Gölbaşı, Adıyaman|Gölbaşı]]", link = "Gölbaşı, Adıyaman", label_size = "80", position = "top" },
	    { lat = "37.780", long = "38.622", mark = "Location dot green.svg", marksize = "12", label = "[[Kâhta]]", link = "Kâhta", label_size = "80", position = "top" },
	    { lat = "38.038", long = "38.616", mark = "Location dot green.svg", marksize = "6", label = "[[Sincik]]", link = "Sincik", label_size = "80", position = "bottom" },
	    { lat = "37.797", long = "37.915", mark = "Location dot green.svg", marksize = "6", label = "[[Tut, Turkey|Tut]]", link = "Tut, Turkey", label_size = "80", position = "right" },
	    { lat = "37.579", long = "38.4825", mark = "Location dot green.svg", marksize = "6", label = "[[Samsat]]", link = "Samsat", label_size = "80", position = "bottom" },
	    { lat = "37.481", long = "38.3175", mark = "BSicon_STRlg_green.svg", marksize = "15", label = "Atatürk Dam", link = "Atatürk Dam", label_size = "0", position = "bottom" },
	    
--oil
	    { lat = "37.841", long = "41.1734", mark = "Gota02.svg", marksize = "9", label = "Batı Raman oil field", link = "Batı Raman oil field", label_size = "0", position = "bottom" },
	    { lat = "38.031", long = "41.6596", mark = "Gota02.svg", marksize = "9", label = "Garzan oil field", link = "Garzan oil field", label_size = "0", position = "bottom" },
	    
--crossings
        { lat = "39.416", long = "44.353", mark = "Mountain pass 12x12 ne.svg", marksize = "18" },
        { lat = "39.416", long = "44.353", mark = "Location dot green.svg", marksize = "7", label = "[[Gürbulak]]", link = "Gürbulak", label_size = "0", position = "bottom" },
        { lat = "41.58", long = "42.820", mark = "Mountain pass 12x12 ne.svg", marksize = "18" },
        { lat = "41.58", long = "42.820", mark = "Location dot green.svg", marksize = "5", label = "[[Türkgözü]]", link = "Türkgözü", label_size = "0", position = "top" },
        { lat = "41.656", long = "26.525", mark = "Mountain pass 12x12 ne.svg", marksize = "16" },
        { lat = "41.656", long = "26.525", mark = "Location dot green.svg", marksize = "6", label = "[[Karaağaç, Edirne|Karaağaç]]", link = "Karaağaç, Edirne", label_size = "0", position = "bottom" },
        { lat = "40.922", long = "26.382", mark = "Mountain pass 12x12 se.svg", marksize = "18" },
        { lat = "40.922", long = "26.382", mark = "Location dot green.svg", marksize = "6", label = "[[İpsala]]", link = "İpsala", label_size = "80", position = "bottom" },
        { lat = "36.711", long = "38.948", mark = "Mountain pass 12x12 n.svg", marksize = "18" },
        { lat = "36.711", long = "38.948", mark = "Location dot green.svg", marksize = "5", label = "[[Akçakale]] <small>(Girê Spî)</small>", link = "Akçakale", label_size = "0", position = "top" },
        { lat = "41.708", long = "26.392", mark = "Mountain pass 12x12 se.svg", marksize = "18" },
        { lat = "41.708", long = "26.392", mark = "Location dot green.svg", marksize = "5", label = "[[Kapıkule]]", link = "Kapıkule", label_size = "0", position = "top" },
        { lat = "36.269", long = "36.567", mark = "Mountain pass 12x12 n.svg", marksize = "18", link = "Cilvegözü Border Crossing", },
        { lat = "36.269", long = "36.567", mark = "Location dot green.svg", marksize = "5", label = "[[Reyhanlı]]", link = "Reyhanlı", label_size = "80", position = "top" },
        { lat = "41.950", long = "26.60", mark = "Mountain pass 12x12 n.svg", marksize = "18" },
        { lat = "41.950", long = "26.60", mark = "Location dot green.svg", marksize = "4", label = "[[Hamzabeyli, Lalapaşa|Hamzabeyli]]", link = "Hamzabeyli, Lalapaşa", label_size = "0", position = "top" },
        { lat = "37.251", long = "43.617", mark = "Mountain pass 12x12 n.svg", marksize = "18" },
        { lat = "37.251", long = "43.617", mark = "Location dot green.svg", marksize = "5", label = "[[Çukurca]] <small>(Çelê)</small>", link = "Çukurca", label_size = "80", position = "top" },
        { lat = "35.903", long = "36.061", mark = "Mountain pass 12x12 n.svg", marksize = "18" },
        { lat = "35.903", long = "36.061", mark = "Location dot green.svg", marksize = "5", label = "[[Yayladağı]]", link = "Yayladağı", label_size = "80", position = "top" },
        { lat = "39.889", long = "44.519", mark = "Mountain pass 12x12 e.svg", marksize = "18" },
        { lat = "39.889", long = "44.519", mark = "Location dot green.svg", marksize = "5", label = "[[Aralık]]", link = "Aralık", label_size = "80", position = "left" },
	    { lat = "41.9672", long = "27.4578", mark = "Mountain pass 12x12 n.svg", marksize = "18" },
        { lat = "41.9672", long = "27.4578", mark = "Location dot green.svg", marksize = "3", label = "[[Dereköy Border Crossing]]", link = "", label_size = "0", position = "left" },
        { lat = "36.834", long = "37.999", mark = "Mountain pass 12x12 n.svg", marksize = "18" },
		{ lat = "36.834", long = "37.999", mark = "Location dot green.svg", marksize = "6", label = "[[Karkamış]]", link = "Karkamış", label_size = "80", position = "left" },
		{ lat = "36.854", long = "40.047", mark = "Mountain pass 12x12 n.svg", marksize = "18" },
		{ lat = "36.854", long = "40.047", mark = "Location dot green.svg", marksize = "10", label = "[[Ceylanpınar]] <small>(Serêkanî)</small>", link = "Ceylanpınar", label_size = "80", position = "top" },
		{ lat = "37.079", long = "41.217", mark = "Mountain pass 12x12 n.svg", marksize = "18" },
		{ lat = "37.079", long = "41.217", mark = "Location dot green.svg", marksize = "8", label = "[[Nusaybin]]", link = "Nusaybin", label_size = "80", position = "top" },
        { lat = "36.644", long = "37.088", mark = "Mountain pass 12x12 n.svg", marksize = "18" },
        { lat = "40.049", long = "43.661", mark = "Location dot green.svg", marksize = "6", label = "[[Tuzluca]]", link = "Tuzluca", label_size = "80", position = "left" },
        { lat = "41.519", long = "41.548", mark = "Mountain pass 12x12 ne.svg", marksize = "18" },
        { lat = "36.644", long = "37.088", mark = "Location dot green.svg", marksize = "4", label = "[[Oncupinar]]", link = "Oncupinar", label_size = "0", position = "bottom" },
        { lat = "37.154", long = "42.568", mark = "Mountain pass 12x12 n.svg", marksize = "18", label = "[[Khabur River|Habur Crossing]]", link = "Khabur River", label_size = "0", position = "bottom" },
        { lat = "41.519", long = "41.548", mark = "Location dot green.svg", marksize = "4", label = "[[Sarp, Hopa|Sarp]]", link = "Sarp, Hopa", label_size = "0", position = "bottom" },
        { lat = "37.083", long = "40.650", mark = "Mountain pass 12x12 n.svg", marksize = "18" },
        { lat = "37.154", long = "42.568", mark = "Location dot green.svg", marksize = "4" },
        { lat = "40.729", long = "43.740", mark = "Mountain pass 12x12 e.svg", marksize = "18", label = "[[Akyaka, Kars|Akyaka Crossing]]", link = "Akyaka, Kars", label_size = "0", position = "bottom" },
        { lat = "37.083", long = "40.650", mark = "Location dot green.svg", marksize = "4", label = "[[Şenyurt]] <small>(Dirbêsî)</small>", link = "Şenyurt", label_size = "0", position = "bottom" },
        { lat = "38.497", long = "44.320", mark = "Mountain pass 12x12 e.svg", marksize = "18", label = "Kapıköy Crossing", link = "Kapıköy Crossing", label_size = "0", position = "bottom" },
        { lat = "40.729", long = "43.740", mark = "Location dot green.svg", marksize = "4", },
        
--nuke 
	    { lat = "39.0772", long = "27.5252", mark = "Icon NuclearPowerPlant-green.svg", marksize = "10", label = "Soma coal mine", link = "Soma coal mine", label_size = "0", position = "bottom" },
	    { lat = "37.5465", long = "35.3987", mark = "Icon NuclearPowerPlant-green.svg", marksize = "10", label = "Aladağ mine", link = "Aladağ mine", label_size = "0", position = "bottom" },
	    { lat = "42", long = "35", mark = "Icon NuclearPowerPlant-green.svg", marksize = "11", label = "Sinop Nuclear Power Plant", link = "Sinop Nuclear Power Plant", label_size = "0", position = "bottom" },
	    { lat = "36.144444", long = "33.541111", mark = "Icon NuclearPowerPlant-green.svg", marksize = "11", label = "Akkuyu Nuclear Power Plant", link = "Akkuyu Nuclear Power Plant", label_size = "0", position = "bottom" },
	    
--airports
		{ lat = "37.097", long = "43.271", mark = "Fighter-jet-green-icon.svg", marksize = "10", label = "[[Bamarni Airbase]]",  label_size = "0", position = "left" },
        { lat = "37.002", long = "35.426", mark = "Fighter-jet-green-icon.svg", marksize = "15", label = "[[Incirlik Air Base]]", link = "Incirlik Air Base", label_size = "0", position = "top" },
        { lat = "37.932", long = "41.116", mark = "Fighter-jet-green-icon.svg", marksize = "15", label = "[[Batman Airport]]", link = "Batman Airport", label_size = "0", position = "top" },
        { lat = "39.815", long = "36.904", mark = "Fighter-jet-green-icon.svg", marksize = "15", label = "[[Sivas Nuri Demirağ Havalimanı Airport]]", link = "Sivas Nuri Demirağ Havalimanı Airport", label_size = "0", position = "top" },
        { lat = "41.187", long = "40.836", mark = "Fighter-jet-green-icon.svg", marksize = "15", label = "[[Rize-Artvin Airport]]", link = "Rize-Artvin Airport", label_size = "0", position = "top" },
        { lat = "40.572", long = "43.088", mark = "Fighter-jet-green-icon.svg", marksize = "15", label = "[[Kars Harakani Airport]]", link = "Kars Harakani Airport", label_size = "0", position = "top" },
	    { lat = "37.910", long = "40.240", mark = "Fighter-jet-green-icon.svg", marksize = "15", label = "[[Diyarbakır Airport]]", link = "Diyarbakır Airport", label_size = "0", position = "top" },
	    { lat = "36.981944", long = "35.280278", mark = "Fighter-jet-green-icon.svg", marksize = "15", label = "[[Adana Şakirpaşa Airport]]", link = "Adana Şakirpaşa Airport", label_size = "0", position = "top" },
	    { lat = "40.128056", long = "32.995", mark = "Fighter-jet-green-icon.svg", marksize = "15", label = "[[Esenboğa International Airport]]", link = "Esenboğa International Airport", label_size = "0", position = "top" },
	    { lat = "40.078889", long = "32.565556", mark = "Fighter-jet-green-icon.svg", marksize = "15", label = "[[Akıncı Air Base]]", link = "Akıncı Air Base", label_size = "0", position = "top" },
	    { lat = "36.362778", long = "36.282222", mark = "Fighter-jet-green-icon.svg", marksize = "15", label = "[[Hatay Airport]]", link = "Hatay Airport", label_size = "0", position = "top" },
	    { lat = "36.900278", long = "30.792778", mark = "Fighter-jet-green-icon.svg", marksize = "15", label = "[[Antalya Airport]]", link = "Antalya Airport", label_size = "0", position = "top" },
	    { lat = "37.250556", long = "27.664167", mark = "Fighter-jet-green-icon.svg", marksize = "15", label = "[[Milas-Bodrum Airport]]", link = "Milas-Bodrum Airport", label_size = "0", position = "top" },
	    { lat = "40.255", long = "29.5625", mark = "Fighter-jet-green-icon.svg", marksize = "15", label = "[[Yenişehir Airport]]", link = "Yenişehir Airport", label_size = "0", position = "top" },
	    { lat = "36.714722", long = "28.792778", mark = "Fighter-jet-green-icon.svg", marksize = "15", label = "[[Dalaman Airport]]", link = "Dalaman Airport", label_size = "0", position = "top" },
	    { lat = "39.955278", long = "41.169167", mark = "Fighter-jet-green-icon.svg", marksize = "15", label = "[[Erzurum Airport]]", link = "Erzurum Airport", label_size = "0", position = "top" },
	    { lat = "39.81", long = "30.519444", mark = "Fighter-jet-green-icon.svg", marksize = "15", label = "[[Anadolu Airport]]", link = "Anadolu Airport", label_size = "0", position = "top" },
	    { lat = "36.947778", long = "37.478889", mark = "Fighter-jet-green-icon.svg", marksize = "15", label = "[[Gaziantep Oğuzeli Airport]]", link = "Gaziantep Oğuzeli Airport", label_size = "0", position = "top" },
	    { lat = "40.9653", long = "38.0804", mark = "Fighter-jet-green-icon.svg", marksize = "15", label = "[[Ordu-Giresun Airport]]", link = "Ordu-Giresun Airport", label_size = "0", position = "top" },
	    { lat = "40.346544", long = "36.342773", mark = "Fighter-jet-green-icon.svg", marksize = "15", label = "[[Tokat Airport]]", link = "Tokat Airport", label_size = "0", position = "top" },
	    { lat = "40.976111", long = "28.814167", mark = "Fighter-jet-green-icon.svg", marksize = "15", label = "[[Atatürk International Airport]]", link = "Atatürk International Airport", label_size = "0", position = "top" },
	    { lat = "40.898333", long = "29.309167", mark = "Fighter-jet-green-icon.svg", marksize = "15", label = "[[Sabiha Gökçen International Airport]]", link = "Sabiha Gökçen International Airport", label_size = "0", position = "top" },
	    { lat = "38.289167", long = "27.155", mark = "Fighter-jet-green-icon.svg", marksize = "15", label = "[[Adnan Menderes International Airport]]", link = "Adnan Menderes International Airport", label_size = "0", position = "top" },
	    { lat = "38.770278", long = "35.495278", mark = "Fighter-jet-green-icon.svg", marksize = "15", label = "[[Erkilet International Airport]]", link = "Erkilet International Airport", label_size = "0", position = "top" },
	    { lat = "37.978889", long = "32.561667", mark = "Fighter-jet-green-icon.svg", marksize = "15", label = "[[Konya Airport]]", link = "Konya Airport", label_size = "0", position = "top" },
	    { lat = "39.111389", long = "30.129722", mark = "Fighter-jet-green-icon.svg", marksize = "15", label = "[[Zafer Airport]]", link = "Zafer Airport", label_size = "0", position = "top" },
	    { lat = "38.435278", long = "38.090833", mark = "Fighter-jet-green-icon.svg", marksize = "15", label = "[[Malatya Erhaç Airport]]", link = "Malatya Erhaç Airport", label_size = "0", position = "top" },
	    { lat = "38.768889", long = "34.526389", mark = "Fighter-jet-green-icon.svg", marksize = "15", label = "[[Nevşehir Kapadokya Airport]]", link = "Nevşehir Kapadokya Airport", label_size = "0", position = "top" },
	    { lat = "41.265556", long = "36.548611", mark = "Fighter-jet-green-icon.svg", marksize = "15", label = "[[Samsun-Çarşamba Airport]]", link = "Samsun-Çarşamba Airport", label_size = "0", position = "top" },
	    { lat = "37.45", long = "38.9", mark = "Fighter-jet-green-icon.svg", marksize = "15", label = "[[Şanlıurfa GAP Airport]]", link = "Şanlıurfa GAP Airport", label_size = "0", position = "top" },
	    { lat = "40.9951", long = "39.7897", mark = "Fighter-jet-green-icon.svg", marksize = "15", label = "[[Trabzon Airport]]", link = "Trabzon Airport", label_size = "0", position = "top" },
	    { lat = "36.541", long = "44.996", mark = "4x4dot-yellow.svg", marksize = "20", label = "[[PKK presence in Qandil Mountains]]", link = "Qandil Mountains", label_size = "0" },--Outside from the map but notable
        { lat = "37.217", long = "43.424", mark = "Abm-green-icon.png", marksize = "6", label = "[[Kanimasi Base(Dilmentepe)]]",  label_size = "0", position = "left" },
	    { lat = "37.172", long = "43.022", mark = "Abm-green-icon.png", marksize = "6", label = "[[Batufa Base]]",  label_size = "0", position = "left" },
		{ lat = "36.490", long = "43.345", mark = "Abm-green-icon.png", marksize = "6", label = "[[Bashiqa Base]]", label_size = "0", position = "left" },
		{ lat = "37.098", long = "43.477", mark = "Abm-green-icon.png", marksize = "6", label = "[[Amediya Base]]",  label_size = "0", position = "left" },
		{ lat = "37.237", long = "43.152", mark = "Abm-green-icon.png", marksize = "6", label = "[[Begova Base]]",  label_size = "0", position = "left" },
	},
	containerArgs = {
		'Turkey',
		AlternativeMap = 'Turkey_adm_location_map.svg',
		float = 'center',
		width = '2500',
		caption = [=['''Hold cursor over location to display name; click to go to sources &/or status description (if available, the cursor will show as [[File:Pointing hand cursor vector.svg|25px]]; if not, it will show as [[File:Cursor.svg|14px]]).'''<br/>
Control
*[[File:Location dot green.svg|11px]] Turkish Republic
*[[File:Dot_yellow_ff4.svg|11px]] [[PKK]] and afiliates
*[[File:Location dot red.svg|11px]] [[DHKP/C]] and [[Maoists]]
*[[File:Location dot black.svg|11px]] [[ISIL]]
*[[File:Map-dot-grey-68a.svg|11px]] [[Turkish Hezbollah|Hezbollah]]

Contested
*[[File:80x80-yellow-green-anim.gif|11px]] Turkish Republic vs [[PKK]]

Stable mixed control
*[[File:Map-ctl2-yellow+green.svg|11px]] Turkey & PKK

Other
*[[File:map-circle-black.svg|12px]] Inner controls, outer sieges (or strong enemy pressure)
*[[File:map-arcNE-black.svg|11px]] Enemy pressure from one side
*[[File:Fighter-jet-black-icon.svg|13px]] Airport/Air base (plane)
*[[File:Helicopter-black-icon.svg|13px]] Heliport/Helicopter base
*[[File:Abm-black-icon.png|13px]] Military base
*[[File:Map-peak-black.svg|11px]] Strategic hill
*[[File:Gota07.svg|12px]] Oil/gas
*[[File:Icon NuclearPowerPlant-black.svg|12px]] Industrial complex
*[[File:Mountain pass 12x12 n.svg|20px]] Border Post
*[[File:Bridge 12x12 n.svg|20px]] Bridge
*[[File:Anchor_pictogram.svg|12px]] Major port or naval base
*[[File:Arch dam 12x12 w.svg|16px]] Dam
*[[File:4x4dot-black.svg|11px]] Rural presence
<br>'''2 nested circles: inner controls, outer sieges (or indicates strong enemy pressure) // 3 nested circles: mixed control with stable situation <br>Small icons within large circle: situation in individual neighborhoods/districts''']=]
-- **TO PREVIEW YOUR EDITS**: type "Template:Turkish Insurgency Detailed Map" into "preview page with this module"

	}
}